### ISSUE TITLE
When i get cookies in thread, i get "Uncaught exception: bad URI(is not URI?): "

### ISSUE THREAD

**Issue by roroco** [teampoltergeist/poltergeist#617] opened 2015-05-01 08:27 UTC
This is my code:
```ruby
require 'capybara/poltergeist'

Capybara.register_driver :p do |app|
  Capybara::Poltergeist::Driver.new(app,
                                    timeout: 1000,
                                    phantomjs_options: %w[--cookies-file=/tmp/phantomjs/cookies.txt],
                                    js_errors: false)
end

s = Capybara::Session.new(:p)
ts = []

s.visit('https://www.google.com')

100.times do |n|
  s.driver.set_cookie("n#{n}", "v#{n}")
  Thread.new do
    s.driver.cookies
  end
end

ts.each do |t|
  t.join
end


```

and I get

```
Uncaught exception: bad URI(is not URI?): [{"domain"=>".www.google.com", "httponly"=>false, "name"=>"n1", "path"=>"/", "secure"=>false, "value"=>"v1"}, {"domain"=>".www.google.com", "httponly"=>false, "name"=>"n0", "path"=>"/", "secure"=>false, "value"=>"v0"}, {"domain"=>".google.com", "expires"=>"Sun, 31 May 2015 08:25:14 GMT", "expiry"=>1433060714, "httponly"=>false, "name"=>"OGPC", "path"=>"/", "secure"=>false, "value"=>"5-1:"}, {"domain"=>".google.com", "expires"=>"Sat, 31 Oct 2015 08:25:08 GMT", "expiry"=>1446279908, "httponly"=>true, "name"=>"NID", "path"=>"/", "secure"=>false, "value"=>"67=gMG-mQEKLmt7OsnXT9k_VerB5kLZfg3wRlSh2qv9yniezpy5Lnfr9Q_hGCPxj6muDdVooZOQP3DhqNWwBy7SEgvp10oCofTiRrlL9Gtm5VTL5HJ5wx_-EE4KpKqBvo5C"}, {"domain"=>".google.com", "expires"=>"Sun, 30 Apr 2017 08:25:08 GMT", "expiry"=>1493540708, "httponly"=>false, "name"=>"PREF", "path"=>"/", "secure"=>false, "value"=>"ID=5f8306b4bc3d274a:FF=0:TM=1430468708:LM=1430468708:S=hbMJzNvasA_vN218"}]
	/home/roroco/.rbenv/versions/2.2.0/lib/ruby/2.2.0/uri/rfc3986_parser.rb:17:in `rescue in split'
	/home/roroco/.rbenv/versions/2.2.0/lib/ruby/2.2.0/uri/rfc3986_parser.rb:14:in `split'
	/home/roroco/.rbenv/versions/2.2.0/lib/ruby/2.2.0/uri/rfc3986_parser.rb:72:in `parse'
	/home/roroco/.rbenv/versions/2.2.0/lib/ruby/2.2.0/uri/common.rb:226:in `parse'
	/home/roroco/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/driver.rb:215:in `set_cookie'
	/home/roroco/Dropbox/rbs/ro_capybara/ex/ex.rb:16:in `block in <top (required)>'
	/home/roroco/Dropbox/rbs/ro_capybara/ex/ex.rb:15:in `times'
	/home/roroco/Dropbox/rbs/ro_capybara/ex/ex.rb:15:in `<top (required)>'
```

**Comment by route** [comment] 2015-05-01 22:27
What versions do you use?

**Comment by roroco** [comment] 2015-05-02 03:57
roroco@roroco ~/Dropbox/rbs/ro_btc $ bundle show poltergeist
/home/roroco/.rbenv/shims/bundle show poltergeist
/home/roroco/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/poltergeist-1.6.0

**Comment by twalpole** [comment] 2015-11-09 18:31
I can't reproduce the error you're getting with the current master branch of Poltergeist, so it may have already been fixed, but your code did cause a hang when multiple threads attempted to receive responses at the same time.  I'm working on a fix for that currently  (also your code doesn't actually push the new threads into ts - so they don't get joined on)

**Comment by twalpole** [comment] 2015-11-09 19:55
I'm going to close this for now since the code appears to run fine with the master branch.  We can reopen if you still have issues.

**Closed by twalpole** 2015-11-09 19:55 UTC
