### ISSUE TITLE
Timeout when using within_frame although iFrame seems to be loaded

### ISSUE THREAD

**Issue by oswaldoferreira** [teampoltergeist/poltergeist#878] opened 2017-03-29 02:24 UTC
I'm trying to use the following code to access an iFrame scope.

```ruby
within_frame(find(:css, "iframe#z_hppm_iframe")) do
  # ...
end
```

And I'm getting (already tried using high timeout values):

```
Capybara::Poltergeist::TimeoutError:
       Timed out waiting for response to {"id":"9d43c2b8-81cb-44b7-8811-03ab7a5beea9","name":"push_frame","args":[[3,104]]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker.
```

Debug log seems to stop on `push_frame` step:

```
{"id":"22372385-d9f5-432a-887e-2094751cd99b","name":"find","args":["css","iframe#z_hppm_iframe"]}
{"command_id":"22372385-d9f5-432a-887e-2094751cd99b","response":{"page_id":3,"ids":[104]}}
{"id":"c216229c-8cb8-4082-8b6a-971e78c973b5","name":"visible","args":[3,104]}
{"command_id":"c216229c-8cb8-4082-8b6a-971e78c973b5","response":true}
{"id":"9d43c2b8-81cb-44b7-8811-03ab7a5beea9","name":"push_frame","args":[[3,104]]}
```

More information on the iFrame being loaded:

![screen shot 2017-03-28 at 11 19 20 pm](https://cloud.githubusercontent.com/assets/1419991/24435698/42c1e386-140d-11e7-8497-774fe74e9206.png)

Obs.: When using `save_and_open_page` I can see that the iFrame is already loaded.

Tried on:
- 1.13
- master

**Comment by twalpole** [comment] 2017-03-29 02:45
What version of Capybara and PhantomJS?

**Comment by oswaldoferreira** [comment] 2017-03-29 02:48
Thanks for the quick answer @twalpole! Capybara 2.13 and PhantomJS 2.1.1.

**Comment by twalpole** [comment] 2017-03-29 03:05
@oswaldoferreira This probably won't fix the issue, but just an FYI -- rather than using a find in within_frame you can just pass it the id of the frame you're looking for and it will use the :frame selector to locate it.  

    within_frame("z_hppm_iframe") do
      # ...
    end

**Comment by twalpole** [comment] 2017-03-29 03:30
@oswaldoferreira  Does sleeping for a few seconds before calling `within_frame` make a difference?

**Comment by oswaldoferreira** [comment] 2017-03-29 03:45
Already tried using about 30 seconds, but no changes.

FYI, it's working on capybara-webkit 1.14.

**Comment by twalpole** [comment] 2017-03-29 17:00
@oswaldoferreira I haven't been able to replicate this, although from reading the code I would guess that either the frame page is requesting a resource that is hanging ( throttled, etc ) or there is a race condition in the page loading.  Could you turn on the `phantomjs_options: ['--debug=true']` option in your driver registration and/or blacklist/whitelist the resources the page is requesting, and let me know if that provides any more info.

**Comment by twalpole** [comment] 2017-03-29 17:11
or (of course) a minimal reproducible example :)

**Comment by twalpole** [comment] 2017-03-29 22:36
@oswaldoferreira  I created a new 'frame_timeout' branch with debugging info around the frame changing code, please give it a try and let me know what it outputs

**Comment by twalpole** [comment] 2017-04-03 19:20
Closing due to lack of response, we will reopen if/when the requested info is provided.

**Closed by twalpole** 2017-04-03 19:20 UTC
Labels: needs-info
