### ISSUE TITLE
Firing click at co ordinate failed, capybara detected another element

### ISSUE THREAD

**Issue by Aadhavan92** [teampoltergeist/poltergeist#809] opened 2016-09-13 06:51 UTC
We tried navigating through handontable using capybara. I tried the following step but still the click fails.

And /^I should see "(.*?)" in the (\d+)(?:st|nd|rd|th) row and (\d+)(?:st|nd|rd|th) col of process grid$/ do |text, row, col|
 field = page.find :xpath, "//div[@id= 'xyz']/div/div/div/div/table/tbody/tr[#{row}]/td[3]"
 field.trigger( :click)
 15.times do
 field.native.send_keys :arrow_right
end
 expect( field ).to have_text text
end

Please help TIA

**Comment by twalpole** [comment] 2016-09-13 08:28
Huh?  What exactly are you trying to do? What does your HTML look like? What version of Capybara and Poltergeist are you using? What is the exact error? What line is causing the error?

**Comment by Aadhavan92** [comment] 2016-09-13 10:56
I am trying to find a particular text inside cell which is at the right most of the handsontable. Since the xpath found is working only for the cells inside the browse view I am using the below code..

And /^I should see "(.*?)" in the (\d+)(?:st|nd|rd|th) row and (\d+)(?:st|nd|rd|th) col of process grid$/ do |text, row, col|
field = page.find :xpath, "//div[@id= div[@id= 'asset-grid-HumrProcess']/div/div/div/div/table/tbody/tr[#{row}]/td[3]" --> **Finding the third cell of the table**
field.trigger( :click) -->  **Clicking it**
22.times do
field.native.send_keys :arrow_right --> **navigating to 22 cells right**
end
expect( field ).to have_text text --> **finding text**
end

Capybara 2.6.2
Poltergiest 1.9.0

**Comment by twalpole** [comment] 2016-09-13 16:40
Ok the correction to 'handsontable' makes it easier to at least have an idea of the HTML you're dealing with, but you still haven't provided the exact error you're getting, or which line is generating the error you're getting.  I'm going to close this for now, when you provide a usable issue report (preferably with a reproducible example) we will reopen.  In the meantime, note that :arrow_right isn't a valid key reference, you probably just want :right - and that calling send_keys :right on the same element 15 or 22 times (your code varies) probably isn't going to move to the cell you want since each time you call send_keys you are resetting the current cell to the one you're sending the key to.

**Closed by twalpole** 2016-09-13 16:40 UTC
Labels: needs-info
