### ISSUE TITLE
Unable to read the PDF in poltergeist

### ISSUE THREAD

**Issue by haridak** [teampoltergeist/poltergeist#689] opened 2015-11-09 21:36 UTC
Hi,
Test env : Capybara-poltergeist + minitest
I am trying to verify a text in  a pdf document. The document gets generated when a link is clicked. Below is the code - 
``` 
within_window(page.window_opened_by{click_link('link that generates pdf in a new browser')}) do

     sleep(30)

    page.html.must_include(facility_name)

    assert_text(facility_name)

    assert_text('Paid-Thru')

    end
 ```

I was able to assert text using capybara and selenium-webdriver by writing something similar to above. However  I am unable to assert the text using capybara-poltergeist.  Could you provide some inputs here?

**Comment by twalpole** [comment] 2015-11-09 22:45
Duplicate of #561

**Closed by twalpole** 2015-11-09 22:45 UTC
