### ISSUE TITLE
Capybara::Poltergeist::DeadClient when JS errors are thrown

### ISSUE THREAD

**Issue by pfleidi** [teampoltergeist/poltergeist#232] opened 2013-01-10 16:30 UTC
Hello,

Some days ago one of our tests using poltergeist started to fail with Capybara::Poltergeist::DeadClient errors.

Here's the code causing the error:

```ruby
  within(:css, "form#node-type-form") do
    fill_in("name", :with => content_type)
    fill_in("description", :with => description)
    click_button("edit-submit")
  end
```

And here's the shell output:

```
      The PhantomJS client died while processing {"args":[2,3],"name":"click"} (Capybara::Poltergeist::DeadClient)
      (eval):2:in `send'
      (eval):2:in `click_button'
      ./features/step_definitions/content_creation_steps.rb:17
      ./features/step_definitions/content_creation_steps.rb:14:in `/^I create a content type named ["']([^"']+)["'] with description ["']([^"']+)["']$/'
      features/fivestar.feature:24:in `And I create a content type named "fivestar-01" with description "fivestar type"'
```

My current setup looks like this:

- Ruby 1.8.7
- Cucumber (1.2.1)
- Capybara (1.1.3)
- Poltergeist (1.0.2)
- PhantomJS 1.8.1

I am running my tests on OS X 10.8 and Ubuntu 8.04.4 LTS. The js_errors option is set to false:

```ruby
  options = {
    :js_errors => false,
    :window_size => [1280, 768],
    :debug => true
  }
```

After debugging the problem a bit more, I found out that a JS error is thrown when loading the site:

```
{"args"=>["http:/my.site/path"], "name"=>"visit"}
{"error"=>{"args"=>[[{"stack"=>"TypeError: 'undefined' is not an object (evaluating 'jQuery.timeago.settings')\n    at http://my.site/sites/all/modules/timeago/timeago.js?mgexlw:13", "message"=>"TypeError: 'undefined' is not an object (evaluating 'jQuery.timeago.settings')"}]], "name"=>"Poltergeist.JavascriptError"}}
Capybara::Poltergeist::JavascriptError
{"args"=>[".//body[contains(concat(' ', @class, ' '), ' logged-in ')]"], "name"=>"find"}
{"response"=>{"ids"=>[0], "page_id"=>1}}
```

After fixing the JS error, the test started working again. So the crash is probably caused by the uncaught error.

I also created [a a crashdump of phantomJS](https://gist.github.com/4501477).

It currently looks like phantomJS dies after encountering a JS error when js_error is set to false.

**Comment by olivierlacan** [comment] 2015-03-01 18:12
@enricostano Still having this issue on ArchLinux? Having it on Ubuntu.

**Comment by enricostano** [comment] 2015-03-02 10:30
sorry @olivierlacan , I gave up on this. Not using Poltergeist anymore. :disappointed:

**Comment by olivierlacan** [comment] 2015-03-03 14:54
Ditto. I don't blame Poltergeist to be fair. I blame PhantomJS.

**Comment by HeroicAutodidact** [comment] 2015-08-12 19:54
This is frustrating. I'm having the same problem and I'm using PhantomJS 1.9.8

How do they not have this fixed? 

What are you guys using instead now?

**Comment by constantm** [comment] 2015-08-24 14:08
We're still getting this randomly on tests running on Semaphore. Not happening on local OSX dev machines.

**Comment by mois3x** [comment] 2015-09-20 00:10
This is weird... still happening randomly when it is used on Rails 3, On rails 4 its ok.

**Comment by twalpole** [comment] 2015-11-13 21:53
Can anyone provide a minimal example that reproduces the issue?  Without that it's pretty hard to fix

**Comment by twalpole** [comment] 2016-01-04 08:58
Closing this due to age, lack of details usable for debugging and the appearance of it most likely being an issue with older phantomjs -- If anyone has a reproducible test case using latest versions of poltergeist/phantomjs please open a new issue

**Closed by twalpole** 2016-01-04 08:58 UTC
Labels: bug, needs-info

**Comment by caseyprovost** [comment] 2016-03-16 23:04
@twalpole I am seeing this issue still, hard to track down.

phantomjs 2.1.1
poltergeist (1.9.0)
capybara (2.5.0)

**Comment by twalpole** [comment] 2016-03-17 00:18
@caseyprovost - What we really need is a reproducible minimal test case

**Comment by Azrasyed** [comment] 2016-04-06 23:35
@twalpole I'm facing the same issue. I'm trying to run my tests on Jenkins.

 Scenario: Adding item to cart and checkout                                       # features/web_checkout.feature:4
    Given I am on the homepage                                                     # features/step_definitions/web_steps.rb:12
    And I submit the registration portal with valid credentials                    # features/step_definitions/signup.rb:1
      Account successfully created
       Email: thrivemarketqa+1459985108@gmail.com
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
    And I submit the password portal with valid credentials                        # features/step_definitions/signup.rb:21
      PhantomJS client died while processing {"id":"5b507f23-6bf4-409b-8a68-5fed2edcaa2b","name":"body","args":[]} (Capybara::Poltergeist::DeadClient)

**Comment by twalpole** [comment] 2016-04-07 00:58
@Azrasyed As stated before -- what we need is a reproducible test case using phantomjs 2.1.1+ -- without that there really is no way for us to figure out whats going on.

**Comment by cmthakur** [comment] 2016-04-29 06:33
@jonleighton @twalpole I'm facing the same issue. I'm trying to run my tests on Jenkins.
My scenarios are same as @Azrasyed, and Gemfile looks like this.
```
phantomjs (2.1.1.0)
poltergeist (1.9.0)
      capybara (~> 2.1)
      cliver (~> 0.3.1)
      multi_json (~> 1.0)
      websocket-driver (>= 0.2.0)
```

Error looks like this:
```
Capybara::Poltergeist::DeadClient:
       PhantomJS client died while processing {"id":"5d43dca7-add2-4280-8192-2ae0cadc15d5","name":"visit","args":["http://localhost:9887/admin/likeman/246/edit",90]}
      # /var/bundle/ruby/2.3.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/server.rb:38:in `send'
     # /var/bundle/ruby/2.3.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/browser.rb:344:in `command'
     # /var/bundle/ruby/2.3.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/browser.rb:34:in `visit'
     # /var/bundle/ruby/2.3.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/driver.rb:95:in `visit'
```

**Comment by volkanunsal** [comment] 2016-05-15 22:42
I came across this issue as well. [Here is the dump file of the error.](https://www.dropbox.com/s/npx77xqfd7o91wo/2CEAF645-CDB8-418B-A833-2E85087E7733.dmp?dl=0)

**Comment by cmthakur** [comment] 2016-05-16 03:26
@jonleighton @twalpole The issue resolved by increasing poltergeist `timeout` value.
```
  options = {
              js_errors: false,
              extensions: [],
              phantomjs_options:['--proxy-type=none', '--load-images=no', '--ignore-ssl-errors=true'],
              timeout: 180,
              window_size: ['1300', '1800'],
              inspector: true,
            }
```

**Comment by volkanunsal** [comment] 2016-05-16 15:07
@cmthakur My timeout is `1000` and still seeing this issue.

**Comment by constantm** [comment] 2016-05-16 15:10
We've done the following and it seems to have helped tremendously with random errors and memory use when running tests:

```ruby
# /spec/spec_helper.rb
config.after :each do |example|
  page.driver.restart if defined?(page.driver.restart)
end
```

This resets PhantomJS completely after each test and has no noticeable performance impact.

**Comment by cmthakur** [comment] 2016-05-17 04:16
@jonleighton @twalpole can you try this in spec_helper.rb, it works for me.

```
   config.after(:each) do
      Capybara.reset_sessions!
      DatabaseCleaner.clean
   end
```

In capybara.rb

```
Capybara.register_driver :poltergeist_debug do |app|
  options = {
              js_errors: false,
              extensions: [],
              phantomjs_options:['--proxy-type=none', '--load-images=no', '--ignore-ssl-errors=true'],
              timeout: 180,
              window_size: ['1300', '1800'],
              inspector: true,
            }
  Capybara::Poltergeist::Driver.new(app, options)
```

**Comment by justin808** [comment] 2016-11-25 23:44
It seems like the key thing is that `js_errors: false`.

I get crashes otherwise in #830.

**Comment by bradens** [comment] 2017-03-15 16:30
Oh my god @constantm you helped me a lot with the trick to restart the driver after each test..been battling unreliable phantomjs crashes for weeks! cheers!

**Comment by dxypher** [comment] 2017-03-27 22:42
Still happening in CircleCI.
Already had js_errors: false, and tried @constantm solution...but no luck.

Difficult to provide steps to reproduce as it happens intermittently and the specs that fail aren't always the same ones.

**Comment by MatzFan** [comment] 2017-11-11 19:37
Restarting the driver, as per @constantm fixed the problem for me (which was caused by forking in my code) but there was a performance hit: ~0.19s on my machine.

**Comment by srish** [comment] 2018-04-28 00:12
In my case only some test cases were problematic, and so it wasn't necessary to include the changes in the `spec_helper.rb` to driver restart after every test case. Building on @constantm's solution, adding the snippet within a context block worked:  

```
context 'user logged in' do
    before(:each) do
        page.driver.restart if defined?(page.driver.restart)
    end
end
```
