### ISSUE TITLE
Specs sporadically failing even with suggested timing handling

### ISSUE THREAD

**Issue by MSchmidt** [teampoltergeist/poltergeist#286] opened 2013-03-25 20:43 UTC
I have this kind of test:

```ruby
scenario '...', js: true do
  visit user_profile_path
  click_on 'Edit profile' # opens a modal with ajax
  page.should have_content('Location') # looks good - always passing this
  fill_in 'Location', with: 'Tokyo'
  click_on 'Save changes' # submits a regular form
  page.should have_selector('#publisher_info', text: 'from Tokyo')
end
```

the last line fails sometimes even though it should sit around and wait for the content to appear (as described [here](https://github.com/jnicklas/capybara#asynchronous-javascript-ajax-and-friends) and [here](http://www.elabs.se/blog/53-why-wait_until-was-removed-from-capybara)). It mostly fails when running the spec for the first time after a while and subsequent runs work well.

**Comment by shepmaster** [comment] 2015-08-10 00:23
Hey lovely maintainers! Is there anything I can do to help this get fixed? I see that @ayasuda was working on creating a reproducible test case; that's great! Maybe we should just finish that and fix up my branch and submit it as a PR?

**Comment by twalpole** [comment] 2015-11-11 23:33
@shepmaster A reproducible test case for this would be great, and would allow it to get fixed

**Comment by twalpole** [comment] 2015-11-12 00:18
The issue here appears to partly be how phantomjs works --   While the poltergeist code is executing the JS execution in the page is paused, until we call sendEvent.  Once sendEvent is called the event is added to the queue and then all current events are handled.  This means that any timer events could be in the event queue ahead of our mouse click and move the element before our click event is processed.  I'm not really sure how we can handle this, since the element can be moved at anytime.  (not sure how this relates to native animations/transitions)

**Comment by twalpole** [comment] 2015-11-12 00:54
We could check after we've sent the click event that the position still refers to the element we wanted to click, and resend to the new location if it's not, but that would then we'd clicked something else first.  Another option would be to raise an error about elements being in motion if the position after didn't match the position before and recommend people disable animations in test mode.  Anyone have any thoughts?

**Comment by twalpole** [comment] 2016-06-25 22:40
Closing this since there is nothing we can do about click locations and moving elements.  Disabling animations in the test environment is the best solution.

**Closed by twalpole** 2016-06-25 22:40 UTC

**Comment by doooby** [comment] 2017-08-23 12:52
just summing up: turn off the offenders, i.e. css animations & transitions, jquery animations, and other that applies to your case.
`
// jquery animations
jQuery.fx.off = true; 

// bootstrap 3 modal
.modal.fade {
   transition: none;
}
.modal.fade .modal-dialog {
  transition: none;
}
`

**Comment by programoo** [comment] 2018-05-09 05:38
For people who run into the same issue:
I use 
`find('.node-name').click`
It works well on selenium driver, the modal is showed up and I can find all elements inside the modal.

However, When I change my JS driver to poltergeist. `find('.node-name').click` does not work anymore.
Fortunately, I change the clicking method to `find('.node-name').trigger(:click)`. It works as expected.

**Comment by twalpole** [comment] 2018-05-09 12:27
@programoo and means your test is now pretty much worthless since it’s no longer testing what a user can actually do
