### ISSUE TITLE
find_field is not finding fields with poltergeist master

### ISSUE THREAD

**Issue by hackeron** [teampoltergeist/poltergeist#295] opened 2013-04-12 09:53 UTC
I have a field:

```html
<input class="radio_buttons required" id="events_time_of_day_business_hours"
 item_wrapper_class="btn" name="events[time_of_day]" type="radio" value="Business Hours">
```

I try to do:

```ruby
find_field("Business Hours")
```

This shows:

```ruby
     Failure/Error: find_field("Business Hours")
     Capybara::ElementNotFound:
       Unable to find field "Business Hours"
```

If I remove js: true (disabling poltergeist), the field can be found correctly. This also works with poltergeist 1.1. The problem seems to have been introduced quite recently in master.

**Comment by xinuc** [comment] 2015-05-08 14:14
still experiencing this :disappointed:

**Comment by twalpole** [comment] 2015-11-16 06:56
Closing due to age and the fact this seems to be a pretty clear case where the item was hidden via CSS -  when not putting js: true the racktest driver would be used which doesn't load/process css files so the element would no longer be considered invisible.  I'm guessing you needed to click something on the page first to make the form appear.  If anyone is sure their element is actually visible when poltergeist thinks it isn't please open a new issue and post all versions details, debug logs, and if possible a minimal reproducible text case

**Closed by twalpole** 2015-11-16 06:56 UTC

**Comment by JannikStreek** [comment] 2015-11-24 13:37
Maybe worth mentioning: I had the same problem (element not found, empty page), for me the path to be visited turned out to be the problem:

Without ```:js => true```, ```visit 'checkout/info```worked
With ```:js => true```, ```visit 'checkout/info```failed
With ```:js => true```, ```visit '/checkout/info```worked (see slash at the beginning)
Without ```:js => true```, ```visit '/checkout/info```failed

So the slash at the beginning seems to be differently interpreted. That was also for me the reason why root_path worked in both cases ;)

**Comment by twalpole** [comment] 2015-11-24 18:08
@JannikStreek If you can produce a minimal example showing that issue please file an issue over on Capybara -  The first 3 examples you give would be expected behavior - a relative path is very different than an absolute path (especially if you have Capybara.app_host set) - but the fourth example should definitely not have failed if the first one passed.
