### ISSUE TITLE
click_button causes unreliable tests vs triggering a click on the object.

### ISSUE THREAD

**Issue by stacia** [teampoltergeist/poltergeist#530] opened 2014-09-03 00:40 UTC
I had a test suite using many tests that used click_button. For a lot of my other suites, I would fall back to using find(whatever).trigger("click") since even finding the button by text would prove to be unreliable. But for this particular suite, it could find the button reliably. Problem is, it didn't click it reliably. I was going crazy trying to find out why in particular this particular suite was so unreliable. It passed every time with the headless webkit driver, Chrome, and Firefox, making me sure this has got to be a poltergeist or PhantomJS thing. I even tried compiling the new 2.x PhantomJS binary from source though, and this didn't fix the issue.

Today I finally think I came across what was causing the tests to be unreliable - I swapped out all the "click_button" calls for the find(whatever).trigger("click") method. The tests are passing in the first time in ages (fingers crossed).

This makes me concerned, though - what is the click_button method doing that is so different than finding a button by css and triggering a click on it? Has anyone else had this issue?

**Comment by AdnanTheExcellent** [comment] 2015-03-18 19:07
Has this been addressed at all? I am having some serious inconsistency problems with my tests now that i upgraded poltergeist to 1.60 (from 1.0.1). 

When i run tests individually, they pass. when i run all my tests, i am getting an error that it can;t find a DOM element when i use find("XXXX").click or click_button "XXXX"

**Comment by RyanSnodgrass** [comment] 2015-06-17 15:11
@AdnanTheExcellent , I've run into a problem like this before with Poltergeist. Using Poltergeist inside a Vagrant machine as Selenium was too much hassle to install Firefox on a command line based OS. Back to your problem, sometimes if my tests don't run correctly all the way through I'll try putting `page.driver.reset!` at the end of my `js: true` tests.

**Comment by xaviershay** [comment] 2015-07-17 01:44
I am seeing this same issue on poltergeist 1.6.0 and websocket-driver 0.6.1.

`click_button` randomly fails to click the button. I confirmed by looking at webserver logs that the expected POST was never received. As such, my subsequent expectation about the content of the page after the POST fails.

`find`/`trigger("click")` appears to work reliably.

I wasn't able to generate debug output ... tried adding `debug: true` to Poltergeist options but didn't seem to do anything. Haven't dug into that yet.

**Comment by shepmaster** [comment] 2015-08-10 00:42
This sounds very similar to #286. The consensus at the end of that issues is that the click request happens during an animation of some kind. There's a race condition in that we ask where the element is, and then request a click at that location. Unfortunately, the element has moved during that time period. 

I have a [half-baked branch](https://github.com/shepmaster/poltergeist/commits/moving-checkboxes) that tries to work around this the hard way, and there's work on a [more reproducible testcase](https://github.com/ayasuda/poltergeist/commit/0a0b0b8141b5251f72e657be72a04cf31308f164).

Maybe some of the activity here can help us squash this issue for good! :smiley_cat:

**Comment by shepmaster** [comment] 2015-08-10 00:44
For reference, one of the ways that I can tell this is an issue is by enabling the Poltergeist debug setting. This logs the coordinates that the click tries for. I also have screenshots of failed tests. I can then look at the coordinate that was clicked and see that it's a number of pixels away from the button that it should be. Perhaps other people can try the same thing to see if the click happens where it is supposed to.

This also explains why `trigger` works - there's no race condition because it's one request that doesn't care where the button is.

**Comment by kswope** [comment] 2015-09-11 00:45
Same problem here, I'm adding this for the record

The below has run for a few days in continuous loop with no problems

```
  specify "email can't be blank" do
    visit('/')
    find_button('Join').trigger('click')
    within('#join-modal') do
      fill_in 'Email', with: ''
      fill_in 'Password', with: 'test'
      fill_in 'Password Confirmation', with: 'test'
      find_button('Join').trigger('click')
      expect(page).to have_content "Email can't be blank"
    end
```

However, if I replace the second

```
find_button('Join').trigger('click')
```

with either

```
click_button('Join')
find_button('Join').click
```

It will fail maybe 1 out of 50 times (just a guess)

The second Join button is in an animated bootstrap4 alpha modal dialog (slides down when appearing), so the animation might have something to do with it.  I don't think I'll ever trust click_button.

**Comment by twalpole** [comment] 2015-09-11 02:19
@kswope That probably is caused by the fact that the button is moving as the modal slides down. If you disable bootstraps animations by setting  $.support.transition = false  when running tests the error will most likely go away.

**Comment by kswope** [comment] 2015-09-11 19:06
@twalpole I didn't disable it but I did give a sleep 1 and that didn't make any difference.  One second for that animation seemed like it should be plenty of time.  I should have showed some improvement.

**Comment by twalpole** [comment] 2015-09-11 20:16
@kswope  Taking a quick look at bootstrap 4 alphas defaults --   I believe the background fade in is set for 0.15 seconds and then the modal fade-in/slide-down is triggered once that is done and is set for .3 seconds -- so 0.45seconds total, so a 1 second sleep should be good enough most of the time (assuming the sleep is right before the second find_button('Join').click - however depending on what the browser is doing I guess it could slip a bit more than half a second (I wouldn't expect over a second) -- did you try putting a 1.5 second sleep and see if the errors stopped (it would be better to disable animations since that would really narrow down animations being the cause - you can just remove the 'fade' classname from the modal to disable it from animating instead)

**Comment by kswope** [comment] 2015-09-13 02:04
@twalpole removing the fade did indeed fix the problem.  However I like my fade, so I'm going back to .trigger('click').  I wonder if the capybara guys could have made this more clear in the click_button docs, i.e. that it depends on positioning and might fail with animations or repositioning during rendering.

**Comment by twalpole** [comment] 2015-09-13 02:34
@kswope it's not a capybara issue, it's a driver specific issue. It don't think it has  happened with the selenium driver, but has happened with both capybara-webkit and poltergeist.  A potential solution is to disable animations in the test environment but leave it active in the production environment. The issue with relying on trigger('click') is that it's no longer replicating user behavior since it's short cutting a bunch of things

**Comment by kswope** [comment] 2015-09-13 20:01
I used this css to remove the animation but still keep the fade.  The tests ran all night in a loop without a single problem.  

```
.modal.fade .modal-dialog {
  -webkit-transform: translate(0, 0);
  -ms-transform: translate(0, 0);
  transform: translate(0, 0);
}
```

**Comment by jmbejar** [comment] 2015-09-21 18:41
Hi everyone,

I'm having this issue and it looks to be related with a modal animation as commented in this discussion.
@kswope Your workaround seems to work in my case.

Anyone is already working on a fix this issue?

**Comment by kswope** [comment] 2015-09-21 21:36
@jmbejar Looks like there are actually three solutions here that worked for me:  

Use   find_button('Join').trigger('click') which gets around the problem by not playing the game of wack-a-mole with the button,

Remove fade from the css, which makes the modal unpleasantly abrupt.

Remove the sliding feature of the fade with the css hack I listed above.

You could probably also sleep for a few seconds before attempting the click, but this wouldn't be reliable as I've found unless its a long sleep.

Honestly I'm not holding my breath for any lower level solutions.  Expecting the drivers to use some heuristic to look for a completion in animation seems like its asking too much.  I settled on the css option of removing the sliding, I think it looks better better anyway- and should probably be an option in bootstrap anyway.

**Comment by route** [comment] 2015-09-29 21:59
@twalpole I think we have such thing as detecting moving elements, at least I remember that

**Comment by twalpole** [comment] 2015-10-12 19:23
@route from reading the code, it calculates the position of the element then verifies that a mouse event (mouseEventTest call) at that position would interact with the specified element (does not verify it would be the middle of that element), and then fires a mouse move event and then a click event.  If using CSS3 animations/transitions (independent of javascript execution) I guess it may be possible for the element to be moving during that time and therefore have moved away from the mouse by the time the mouse move and click events occur, although I have not been able to create a test case for it.   It's possible to have mouseEventTest verify that the event would occur in the middle of the element, which may detect the motion, but without a reliable test case it would just be guessing.  Also that would potentially make clicking on elements that are continuously moving impossible.

**Comment by twalpole** [comment] 2015-11-11 23:28
There have been a few changes around clicking and message responses on the master branch recently - has this fixed any of the issues people are reporting in this thread?  If not, can you provide a minimal example that exhibits the issue so I can figure out whats happening?

**Comment by route** [comment] 2015-11-12 20:45
@twalpole I agree with previous comment btw :)

**Comment by twalpole** [comment] 2016-06-17 00:01
Closing this since there's nothing we can really do about moving elements and clicks - The best solution is to conditionally disable animations in the test environment -   `jQuery.fx.off = true` and `$.support.transition = false' can be your friends here

**Comment by naw** [comment] 2016-06-17 00:01
Just FYI, I'm seeing similar behavior where a test against a page rendered with React is clicking in the wrong place.

Although there are no animations, the positioning of elements can quickly shift when React renders other content higher in the page. Presumably this results in a similar race condition as occur with animations, where `mouseEventTest` succeeds, but the element shifts to a new position immediately thereafter before the click occurs.

In this particualr case I'm using `find(selector).click` rather than `click_button`, but I'm assuming the same issue applies.

**Closed by twalpole** 2016-06-17 00:01 UTC

**Comment by naw** [comment] 2016-06-17 00:10
So `trigger('click')` is a good workaround, but you lose the ability to ensure that your element is actually clickable (i.e. not covered by something else).

Perhaps the "best of both worlds" would be a `mouseEventTest` coupled with a `trigger('click')`, which would do a fairly decent job of ensuring your element is clickable while not being susceptible to animation and/or other DOM change race conditions?   Or, perhaps a way to opt-in to such behavior?

**Comment by twalpole** [comment] 2016-06-17 01:02
@naw Yes click_button is implemented as find(...).click so they're the same.  The problem with your suggestion is that trigger('click') isn't really the same event that a user would generate (as a start it has no mouse position set in the event) - Are you sure you don't have any animations involving the item you're trying to click (or containing elements) (no jQuery.show for instance?) - I guess it could be react updating things in the page, but it seems like that would be predictable in a test since you're the one changing the data driving the react updates.

**Comment by naw** [comment] 2016-06-17 16:49
@twalpole thanks for your response.

**Regarding my particular situation**: Yes, definitely not jQuery related --- just a chunk of DOM that gets inserted higher in the page in response to an AJAX call.  You're correct that I'm driving the data, and I _could_ solve the race condition by explicitly waiting for that content to appear, but ideally, when we write specs, we don't want to have to think about all the other things on the page that are unrelated to what we're testing, nor do we want to solve these kinds of things on a case-by-case basis, if it's feasible to solve them more generally.  Of course, as you pointed out last night in your close message, perhaps there _isn't_ a general solution.

**Regarding my suggestion**: I think what you're saying is that `trigger(:click)` isn't an acceptable general workaround (i.e. it wouldn't work for at least some people) because they need a _real_ click in order for their JavaScript on the page to work correctly?   Yes, that makes sense --- thanks for pointing that out.

As far as supporting such a workaround for people who don't need real clicks, but still want to ensure the element is clickable (i.e. not covered by something else), is there any way to expose something on the driver that would allow us to initiate a `mouseTestEvent` directly (without the associated click), so that in user land we could write a helper method that combines a `mouseTestEvent` and a `trigger(:click)`  ?

e.g. something like this:

```ruby
def clickWorkaround
  mouseTestEvent
  trigger(:click)
end
```

**Comment by twalpole** [comment] 2016-06-18 17:38
@naw - adding access to mouseTestEvent to the driver is definitely possible, but would need to be called something like `page.driver.mouseTestEvent(element)` to clarify that this is not Capybara standard and will not work with other drivers.  I'm not really convinced it's a great idea since it really just moves the race conditions to other places, however PRs are always considered.

**Comment by doooby** [comment] 2017-08-23 12:52
just summing up: turn off the offenders, i.e. css animations & transitions, jquery animations, and other that applies to your case.

```
// jquery animations
jQuery.fx.off = true; 

// bootstrap 3 modal
.modal.fade {
   transition: none;
}
.modal.fade .modal-dialog {
  transition: none;
}
```
