### ISSUE TITLE
Using default address 127.0.0.1 leads to cookies problems when using Capybara.server_host

### ISSUE THREAD

**Issue by woto** [teampoltergeist/poltergeist#503] opened 2014-06-07 04:58 UTC
Hi, sorry for bad English. Not sure that this is a bug, in my project i'm using 

```
Capybara.server_port = 3000
Capybara.server_host = 'localhost'
```

next i wanted to set cookie

```
page.driver.set_cookie "auth_token", "8e9beU3E20YWHmF1RBSwFa"
```

i found that this doesn't work. 
Next I found the problem. Because of different hosts.

poltergeist-c3d41c7652c4/lib/capybara/poltergeist/driver.rb @ line 218 Capybara::Poltergeist::Driver#set_cookie:

```
Capybara.app_host || "127.0.0.1"
```

After changing server_host from 'localhost' to '127.0.0.1' all works fine.

**Comment by Jamedjo** [comment] 2015-03-18 19:33
I'm having similar issues in that using app_host or default_host prevents cookies from being set/retrieved.

Resetting them to `127.0.0.1` before the test works:

    Capybara.default_host = 'http://127.0.0.1'
    Capybara.app_host = 'http://127.0.0.1'
    page.driver.set_cookie('my_cookie_name', 'cookiemonster', domain: '127.0.0.1')

Where as setting a subdomain doesn't work:

    Capybara.default_host = 'http://ourdomain.com'
    Capybara.app_host = 'http://ourdomain.com'
    page.driver.set_cookie('my_cookie_name', 'cookiemonster', domain: 'ourdomain.com')

**Comment by twalpole** [comment] 2015-11-16 06:49
This seems to be a combination of 2 issues - one is #217 which is a phantomjs issue with cookie setting and not yet sure whether we can do anything about that.  The second is that the host you're visiting and the host you're setting cookies for have to match.  Capybara.server_host is the ip/host that capybara attempts to bind the server to when it's running an app, Capybara.app_host is the url that gets prepended to paths passed to visit and is mainly designed for use when testing external sites.  Capybara.default_host is used by the racktest driver (but will be overridden by app_host if set).  I'm closing this since the one part of this issue is a configuration problem and not an issue in poltergeist and the other is a duplicate of issue #217

**Closed by twalpole** 2015-11-16 06:49 UTC
