### ISSUE TITLE
Incompatibility with rspec 3.4.0: wrong number of arguments (3 for 2)

### ISSUE THREAD

**Issue by ronwsmith** [teampoltergeist/poltergeist#702] opened 2015-11-18 20:12 UTC
Relevant errors:

```ruby
lib/capybara/poltergeist/errors.rb:17:in `initialize': wrong number of arguments (3 for 2) (ArgumentError) 
lib/capybara/poltergeist/errors.rb:33:in `new' 
lib/capybara/poltergeist/errors.rb:33:in `javascript_error' 
lib/capybara/poltergeist/errors.rb:39:in `message' 

lib/rspec/core/formatters/exception_presenter.rb:52:in `formatted_cause' 
lib/rspec/core/formatters/exception_presenter.rb:39:in `formatted_backtrace' 
```

Full backtrace:

```ruby
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/poltergeist-1.8.0/lib/capybara/poltergeist/errors.rb:17:in `initialize': wrong number of arguments (3 for 2) (ArgumentError) 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/poltergeist-1.8.0/lib/capybara/poltergeist/errors.rb:33:in `new' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/poltergeist-1.8.0/lib/capybara/poltergeist/errors.rb:33:in `javascript_error' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/poltergeist-1.8.0/lib/capybara/poltergeist/errors.rb:39:in `message' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/formatters/exception_presenter.rb:52:in `formatted_cause' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/formatters/exception_presenter.rb:39:in `formatted_backtrace' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/formatters/exception_presenter.rb:70:in `colorized_formatted_backtrace' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/formatters/exception_presenter.rb:229:in `formatted_message_and_backtrace' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/formatters/exception_presenter.rb:84:in `fully_formatted_lines' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/formatters/exception_presenter.rb:76:in `fully_formatted' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/notifications.rb:200:in `fully_formatted' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/notifications.rb:114:in `block in fully_formatted_failed_examples' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/notifications.rb:113:in `each' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/notifications.rb:113:in `each_with_index'
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/notifications.rb:113:in `fully_formatted_failed_examples' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/formatters/base_text_formatter.rb:33:in `dump_failures' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/reporter.rb:189:in `block in notify' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/reporter.rb:188:in `each' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/reporter.rb:188:in `notify' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/reporter.rb:160:in `block in finish' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/reporter.rb:175:in `close_after' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/reporter.rb:156:in `finish' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/reporter.rb:79:in `report' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/runner.rb:113:in `run_specs' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/runner.rb:89:in `run' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/runner.rb:73:in `run' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/lib/rspec/core/runner.rb:41:in `invoke' 
        from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.0/exe/rspec:4:in `<top (required)>'
```

**Comment by twalpole** [comment] 2015-11-18 20:24
I don't think this has anything to do with rspec version -- could you run with debug turned on for poltergeist and post the part where the javacript error is returned please

**Comment by williscool** [comment] 2015-11-19 21:20
I had this issue issue too. But only when trying to run with 

https://github.com/ci-reporter/ci_reporter_rspec

Will do the debug mode thing if I have time later today.

I'm positive it has something to do with rspec's trace output formattter because I got exactly the stacktrace

**Comment by twalpole** [comment] 2015-11-19 21:29
It could be that rspec is now displaying a message description that it didn't previously, but it's definitely an error in Poltergeist calling an error object constructor with more parameters than needed.  I just need to know what kind of error poltergeist is actually returning (which will hopefully be shown in the debug output) to know where to fix it.

**Comment by ronwsmith** [comment] 2015-11-19 21:54
Poltergeist debug info right before the error:

```ruby
{"id":"564d34ca-b485-4c4f-9139-00d49bc2b14f","name":"render","args":["/Users/.../tmp/capybara/screenshot_2015-11-19-15-45-19.863.png",true,null]}
{"command_id":"564d34ca-b485-4c4f-9139-00d49bc2b14f","response":true}
{"id":"78b3be04-1e16-4d57-8940-c91374b1f0d9","name":"reset","args":[]}
{"command_id":"78b3be04-1e16-4d57-8940-c91374b1f0d9","response":true}
{"id":"f588604e-5266-4e6a-aea0-5c67dabf0289","name":"find","args":["xpath","/html/body/*"]}
{"command_id":"f588604e-5266-4e6a-aea0-5c67dabf0289","response":{"page_id":0,"ids":[]}}
    XXX (FAILED - 1)
  HTML screenshot: file:///Users/.../tmp/capybara/screenshot_2015-11-19-15-45-19.863.html
  Image screenshot: file:///Users/.../tmp/capybara/screenshot_2015-11-19-15-45-19.863.png
```

I also use ci_reporter_rspec, but when removing it, the error persists.  Error also occurs if I remove capybara-screenshot gem too.  Error does not occur when I downgrade from rspec 3.4.1 (was 3.4.0 yesterday) to 3.3.0.

**Comment by ronwsmith** [comment] 2015-11-19 22:04
Note: I do have several of these errors, but when on rspec 3.3.0, the error is reported at the end of the run correctly:

```ruby
{"command_id":"8d42967b-6ddd-47a5-850f-4935a2015ba8","error":{"name":"Poltergeist.MouseEventFailed","args":["click","html.js.flexbox.flexboxlegacy.canvas.canvastext.no-webgl.touch.no-geolocation.postmessage.websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.cssreflections.csstransforms.no-csstransforms3d.csstransitions.fontface.generatedcontent.no-video.no-audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.js.flexbox.flexboxlegacy.canvas.canvastext.no-webgl.touch.no-geolocation.postmessage.websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.cssreflections.csstransforms.no-csstransforms3d.csstransitions.fontface.generatedcontent.no-video.no-audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths body.application-flow.simple-header nav.navbar.navbar-default.navbar-fixed-top.simple div.container div.row",{"x":712.5,"y":41}]}}
```

**Comment by twalpole** [comment] 2015-11-19 23:00
hmmm -- I'm not sure if it's the XXX (FAILED = 1) part of that log or what - it shouldn't be the Poltergeist.MouseEventFailed responses since they're handled separately - Not really sure any of that log is showing the error thats causing the issue.

**Comment by twalpole** [comment] 2015-11-19 23:30
Could you please try running using my 'rspec3_4' branch 

gem 'poltergeist', github: 'twalpole/poltergeist', branch: 'rspec3_4'

and then post the output that has   'ERROR ERROR ERROR ERROR' around it -- it'll probably have "There was an error inside the PhantomJS portion of Poltergeist ... " before it

**Comment by jodonnell** [comment] 2015-11-23 15:27
i had this problem, rspec 3.4.0, no ci_reporter_rspec.  USing your rspec3_4 branch it worked fine.

**Comment by twalpole** [comment] 2015-11-23 19:50
@jodonnell Sorry about that, could you please try again - I forgot to add a reader

**Comment by jodonnell** [comment] 2015-11-23 20:35
with this branch i get the correct error:
Firing a click at co-ordinates [1002, 26] failed. Poltergeist detected another element with CSS selector '....' at this position. It may be overlapping the element you are trying to interact with. If you don't care about overlapping elements, try using node.trigger('click').

# ------------------
     # --- Caused by: ---
     # Capybara::Poltergeist::BrowserError:
     #   There was an error inside the PhantomJS portion of Poltergeist. This is probably a bug, so please report it. 
     #   
     #   Poltergeist.MouseEventFailed: ERROR ERROR ERROR ERROR
     #   click
     #   html the_rest_of_the_css_selector
     #   {"x"=>1002, "y"=>26}
     #   ERROR ERROR ERROR ERROR

**Comment by twalpole** [comment] 2015-11-23 20:39
@jodonnel  Thanks -- that gives me something to go on to fix this properly

**Comment by twalpole** [comment] 2015-11-23 22:34
Ok -- this error is caused by rspec now recursing up the cause chain of exceptions when displaying

**Comment by twalpole** [comment] 2015-11-23 23:53
I've merged in what I think should fix this issue to the master branch - If someone can confirm it fixes the issue for them I'll release a new gem.

**Comment by williscool** [comment] 2015-11-24 00:38
whose awesome @twalpole is awesome

**Comment by ronwsmith** [comment] 2015-11-24 04:24
@twalpole, master no longer returns the error in this issue and I see your new messaging and proper error from https://github.com/teampoltergeist/poltergeist/pull/705.  I do have something separate only occurring after 1.7.0 but I will open a new issue after more investigation.

Really appreciate the fast turnaround time.  Please close this issue once the new gem is cut.

**Comment by twalpole** [comment] 2015-11-24 17:58
1.8.1 released with the fix for this.

**Closed by twalpole** 2015-11-24 17:58 UTC
Labels: bug
