### ISSUE TITLE
Using document.querySelector(All) with invalid selector fails silently

### ISSUE THREAD

**Issue by mcmire** [teampoltergeist/poltergeist#820] opened 2016-10-26 22:15 UTC
I have an app that has quite a bit of JavaScript, and I ran into a strange issue just now. When I ran one of my feature tests, it stopped short, saying it couldn't find a certain element on the page. I initially thought this had to do with CSS transitions/animations, but after disabling them the problem remained. Eventually I pinpointed the issue to a line of code where I was using `document.querySelector` to find an element on the page, but using an invalid selector. It looked something like this:

``` javascript
document.querySelector("[data-foo")
```

A few judicious `console.log`'s revealed that any JavaScript beyond this point was actually never getting executed in the tests, as though it never existed. When I added the missing `]`, everything went back to normal and my feature test was able to get a lot further than it did.

Something worth noting is that if you execute `document.querySelector("[data-foo")` in the browser, you don't get an error, you will simply get nothing back:

``` javascript
document.querySelector("[data-foo")    //=> null
```

So that makes this issue tricky to debug. Regardless of this, the functionality in my app that I'm testing works fine in the browser. Even though leaving the closing bracket is obviously a bug in my code, it isn't preventing JavaScript after that point from getting executed. I am only seeing that when running tests.

Has anyone else seen this issue? Could this be a bug in Phantom?

**Comment by twalpole** [comment] 2016-10-26 22:38
Firefox and Chrome both ignore the illegal selector and just return null, Safari and PhantomJS (both built on WebKit) raise an error for the illegal selector - so whether or not you consider that a bug is up to interpretation without looking through a bunch of specs to try and figure out whether it should or should not raise an error.  My guess is you have configured your poltergeist driver with `js_errors: false` thereby telling it to swallow any JS errors.

**Comment by mcmire** [comment] 2016-10-27 01:36
Okay, good to know. Two things:

* I know about that setting, but I didn't have it set in this case.
* If WebKit is supposed to raise an error, then Poltergeist didn't expose that.

**Comment by twalpole** [comment] 2016-10-27 02:07
If you can create a simple example showing the issue we can take a look at it.  Something like  https://gist.github.com/twalpole/9a79ca9d4fa0b090f0bcc8ca10f47bdc would be a good starting point.

**Comment by mcmire** [comment] 2016-10-27 02:09
Cool, I'll do that and let you know.

**Comment by twalpole** [comment] 2016-10-27 18:56
Closing for now since it doesn't actually appear to be a poltergeist issue.  We can reopen if a reproducible examples shows that it is.

**Closed by twalpole** 2016-10-27 18:56 UTC
