### ISSUE TITLE
Position of button incorrectly calculated (with code to reproduce)

### ISSUE THREAD

**Issue by marcandre** [teampoltergeist/poltergeist#738] opened 2016-02-17 22:27 UTC
When attempting to move an extensive test suite for Bandzoogle from `capybara-webkit` to `poltergeist`, we got a bunch of failures. Some of them where helpful actually, it's nice that poltergeist is stricter in that respect.

While tweaking our specs, we discovered a bug whereby we can no longer click on a button because poltergeist computes the wrong *y* coordinate for the button.

I did a lot more work that I had hoped for to figure out what was necessary to reproduce it and isolate what's needed, but it's all here [in this branch](https://github.com/marcandre/poltergeist/tree/very_fragile_bug). The spec [`integration/bz_spec.rb`](https://github.com/marcandre/poltergeist/blob/very_fragile_bug/spec/integration/bz_spec.rb) fails although it should not.

The spec loads `/controlpanel/bz` and then does a couple of steps that fires ajax requests:
1) click on 'next' (end of page)
2) click on 'Delete comment' of the last comment
3) click on 'Approve comment' of the last comment
4) attempts to click on 'All' (top of the list)

The last step fails because **poltergeist computes the wrong y coordinate for the button** (*y* of 26 instead of 184). Note that **jQuery returns the right `offset().top`**, as you can see in the output.

Now this failing spec is outrageously brittle in showing the bug. If any of the following is done, the bug disappears:
* skip any of step 1, step 2 or step 3 (you can't test easily skipping the first step, you'll have to believe me)
* remove the "positive: fixed" css for the `#page-header`
* call `@session.save_screenshot` before attempting to click on 'All' :astonished: :bomb:

Because of this brittleness, I made no effort to minimize the ridiculous amount of JS code going on in all steps, or the extensive markup. I hope that nevertheless this can be helpful in finding a bug that could impact others. I'll personally offer a :beer: or three to anyone that fixes this.

PS: I'll never admit writing any of this code.

**Comment by marcandre** [comment] 2016-02-17 22:28
PPS: Here's the output I get...
```
$ DEBUG=t rspec spec/integration/bz_spec.rb 
Run options: exclude {:requires=>#<Proc:0x007fb9dcf7b5f0>}
Next refresh will be bz_next
Responding with bz_next
Next refresh will be bz_after_delete
Responding with bz_after_delete
Next refresh will be bz_after_approve
Responding with bz_after_approve
**** Top of All button is at: 184
{"id":"ed3e1956-17ea-415a-bfc7-4c99d3245a52","name":"set_debug","args":[true]}
{"command_id":"ed3e1956-17ea-415a-bfc7-4c99d3245a52","response":true}
{"id":"797840ea-91e8-41f0-9984-7b47e03014d6","name":"visit","args":["http://127.0.0.1:60016/controlpanel/bz"]}
{"command_id":"797840ea-91e8-41f0-9984-7b47e03014d6","response":{"status":"success"}}
{"id":"53f01bbe-de83-4106-8b66-850226d51256","name":"execute","args":["$.fx.off = true"]}
{"command_id":"53f01bbe-de83-4106-8b66-850226d51256","response":true}
{"id":"1e27dcc3-8a96-4b92-8756-60ed983dba96","name":"find","args":["xpath",".//a[./@href][(((./@id = 'Next' or normalize-space(string(.)) = 'Next') or ./@title = 'Next') or .//img[./@alt = 'Next'])] | .//input[./@type = 'submit' or ./@type = 'reset' or ./@type = 'image' or ./@type = 'button'][((./@id = 'Next' or ./@value = 'Next') or ./@title = 'Next')] | .//input[./@type = 'image'][./@alt = 'Next'] | .//button[(((./@id = 'Next' or ./@value = 'Next') or normalize-space(string(.)) = 'Next') or ./@title = 'Next')] | .//input[./@type = 'image'][./@alt = 'Next']"]}
{"command_id":"1e27dcc3-8a96-4b92-8756-60ed983dba96","response":{"page_id":1,"ids":[0]}}
{"id":"c5b8d7a2-97c5-4556-8f6f-2c6aa66703dd","name":"visible","args":[1,0]}
{"command_id":"c5b8d7a2-97c5-4556-8f6f-2c6aa66703dd","response":true}
{"id":"f919aa14-b14a-4aeb-9c25-4a4064f18002","name":"tag_name","args":[1,0]}
{"command_id":"f919aa14-b14a-4aeb-9c25-4a4064f18002","response":"A"}
{"id":"0e6cb1cb-6ceb-4291-b7a3-5bd92ca09b0f","name":"click","args":[1,0]}
{"command_id":"0e6cb1cb-6ceb-4291-b7a3-5bd92ca09b0f","response":{"position":{"x":305.5,"y":696}}}
{"id":"d7aa4029-36ce-4f15-b412-7a04d8b7d4a1","name":"find","args":["xpath","/html"]}
{"command_id":"d7aa4029-36ce-4f15-b412-7a04d8b7d4a1","response":{"page_id":1,"ids":[1]}}
{"id":"f2fa448b-ba26-4e54-96e5-e35d9ed2bfde","name":"visible","args":[1,1]}
{"command_id":"f2fa448b-ba26-4e54-96e5-e35d9ed2bfde","response":true}
{"id":"4ae56038-3b69-4560-8ace-427bba105965","name":"visible_text","args":[1,1]}
{"command_id":"4ae56038-3b69-4560-8ace-427bba105965","response":" \nPages\nDesign\nFans\nReports\nCommunity\nAccount\nHelp\n View site\n  \nBack\nManage guestbook\nOptions\nNotify me of new posts: Yes\nScreen posts: Yes\nAllow anonymous posts: Yes\nedit display options\n\n \t\nGuestbook: Manage guestbook\nAll 31\nUnapproved 15\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {10}\nRandom comment #22!\n\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {8}\nRandom comment #24!\n\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {6}\nRandom comment #26!\n\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {4}\nRandom comment #28!\n\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {2}\nRandom comment #30!\n\nFirst Prev 1 2\n "}
{"id":"6e17e31d-1415-4506-a440-015ae55908c6","name":"find","args":["css","#comment_1599 .interaction_link.destroy_link i"]}
{"command_id":"6e17e31d-1415-4506-a440-015ae55908c6","response":{"page_id":1,"ids":[2]}}
{"id":"83a9e7a1-3f4f-4898-acd7-66c5620283ac","name":"visible","args":[1,2]}
{"command_id":"83a9e7a1-3f4f-4898-acd7-66c5620283ac","response":true}
{"id":"60dba002-7a3e-4582-8e2b-7ede62176633","name":"click","args":[1,2]}
{"command_id":"60dba002-7a3e-4582-8e2b-7ede62176633","response":{"position":{"x":973.5,"y":595}}}
{"id":"90d7156e-bafd-44b8-b828-5d3971dae51b","name":"find","args":["xpath","/html"]}
{"command_id":"90d7156e-bafd-44b8-b828-5d3971dae51b","response":{"page_id":1,"ids":[3]}}
{"id":"efda261d-460e-48fb-8309-9412698afe80","name":"visible","args":[1,3]}
{"command_id":"efda261d-460e-48fb-8309-9412698afe80","response":true}
{"id":"035825c8-ea65-4726-8dc1-3abf04863356","name":"visible_text","args":[1,3]}
{"command_id":"035825c8-ea65-4726-8dc1-3abf04863356","response":" \nPages\nDesign\nFans\nReports\nCommunity\nAccount\nHelp\n View site\n  \nBack\nManage guestbook\nOptions\nNotify me of new posts: Yes\nScreen posts: Yes\nAllow anonymous posts: Yes\nedit display options\n\n \t\nGuestbook: Manage guestbook\nAll 31\nUnapproved 15\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {10}\nRandom comment #22!\n\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {8}\nRandom comment #24!\n\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {6}\nRandom comment #26!\n\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {4}\nRandom comment #28!\n\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {2}\nRandom comment #30!\n\nFirst Prev 1 2\nDelete?\nAre you sure you want to delete this item?\nDeletecancel\n"}
{"id":"57003dfa-5600-4214-9083-7d07eabeb2ef","name":"find","args":["css","#zoogle_dialog a.negative"]}
{"command_id":"57003dfa-5600-4214-9083-7d07eabeb2ef","response":{"page_id":1,"ids":[4]}}
{"id":"47e0c3d8-693b-42a8-8111-a65319a139ff","name":"visible","args":[1,4]}
{"command_id":"47e0c3d8-693b-42a8-8111-a65319a139ff","response":true}
{"id":"a5d7f22a-569e-49eb-b001-d6d842a7f83a","name":"click","args":[1,4]}
{"command_id":"a5d7f22a-569e-49eb-b001-d6d842a7f83a","response":{"position":{"x":480.5,"y":413}}}
{"id":"f17573ce-51c3-4c86-b665-e8bc829e1fee","name":"find","args":["xpath","/html"]}
{"command_id":"f17573ce-51c3-4c86-b665-e8bc829e1fee","response":{"page_id":1,"ids":[5]}}
{"id":"1d2643bd-69c0-4378-b843-1ffd8f78d2a8","name":"visible","args":[1,5]}
{"command_id":"1d2643bd-69c0-4378-b843-1ffd8f78d2a8","response":true}
{"id":"b8f9e3bb-e63a-4a8b-8f3a-6f9b6bd71f65","name":"visible_text","args":[1,5]}
{"command_id":"b8f9e3bb-e63a-4a8b-8f3a-6f9b6bd71f65","response":" \nPages\nDesign\nFans\nReports\nCommunity\nAccount\nHelp\n View site\n  \nBack\nManage guestbook\nOptions\nNotify me of new posts: Yes\nScreen posts: Yes\nAllow anonymous posts: Yes\nedit display options\n\n \t\nDeletion worked\nGuestbook: Manage guestbook\nAll 30\nUnapproved 14\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {10}\nRandom comment #22!\n\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {8}\nRandom comment #24!\n\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {6}\nRandom comment #26!\n\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {4}\nRandom comment #28!\n\nFirst Prev 1 2\n "}
{"id":"7238c30a-2ff8-4a03-87d8-14644cda7948","name":"find","args":["xpath","/html"]}
{"command_id":"7238c30a-2ff8-4a03-87d8-14644cda7948","response":{"page_id":1,"ids":[6]}}
{"id":"c2edf930-59d3-4151-93bf-f07968444982","name":"visible","args":[1,6]}
{"command_id":"c2edf930-59d3-4151-93bf-f07968444982","response":true}
{"id":"3ec84aba-03ad-438c-abdd-330f6d0957c1","name":"visible_text","args":[1,6]}
{"command_id":"3ec84aba-03ad-438c-abdd-330f6d0957c1","response":" \nPages\nDesign\nFans\nReports\nCommunity\nAccount\nHelp\n View site\n  \nBack\nManage guestbook\nOptions\nNotify me of new posts: Yes\nScreen posts: Yes\nAllow anonymous posts: Yes\nedit display options\n\n \t\nDeletion worked\nGuestbook: Manage guestbook\nAll 30\nUnapproved 14\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {10}\nRandom comment #22!\n\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {8}\nRandom comment #24!\n\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {6}\nRandom comment #26!\n\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {4}\nRandom comment #28!\n\nFirst Prev 1 2\n "}
{"id":"f40e6396-cc56-4241-9096-f55b80d07d5c","name":"find","args":["css","#comment_1601"]}
{"command_id":"f40e6396-cc56-4241-9096-f55b80d07d5c","response":{"page_id":1,"ids":[7]}}
{"id":"9a9cca5a-8e82-44ca-99da-225c2925d09d","name":"visible","args":[1,7]}
{"command_id":"9a9cca5a-8e82-44ca-99da-225c2925d09d","response":true}
{"id":"aae2ab92-6f5e-4560-b7df-651605156c61","name":"find_within","args":[1,7,"xpath",".//a[./@href][(((./@id = 'Approve comment' or normalize-space(string(.)) = 'Approve comment') or ./@title = 'Approve comment') or .//img[./@alt = 'Approve comment'])] | .//input[./@type = 'submit' or ./@type = 'reset' or ./@type = 'image' or ./@type = 'button'][((./@id = 'Approve comment' or ./@value = 'Approve comment') or ./@title = 'Approve comment')] | .//input[./@type = 'image'][./@alt = 'Approve comment'] | .//button[(((./@id = 'Approve comment' or ./@value = 'Approve comment') or normalize-space(string(.)) = 'Approve comment') or ./@title = 'Approve comment')] | .//input[./@type = 'image'][./@alt = 'Approve comment']"]}
{"command_id":"aae2ab92-6f5e-4560-b7df-651605156c61","response":[8]}
{"id":"35aa8082-e5d2-45af-9358-22894c7dbe65","name":"visible","args":[1,8]}
{"command_id":"35aa8082-e5d2-45af-9358-22894c7dbe65","response":true}
{"id":"43f2dfe9-969a-44b5-851b-d03598c6257c","name":"tag_name","args":[1,8]}
{"command_id":"43f2dfe9-969a-44b5-851b-d03598c6257c","response":"A"}
{"id":"4d38bfe0-99c9-4f92-aed2-ff15f32cfc36","name":"click","args":[1,8]}
{"command_id":"4d38bfe0-99c9-4f92-aed2-ff15f32cfc36","response":{"position":{"x":751,"y":564}}}
{"id":"3765f41f-9932-4b17-82b5-3839a72ac8b0","name":"find","args":["xpath","/html"]}
{"command_id":"3765f41f-9932-4b17-82b5-3839a72ac8b0","response":{"page_id":1,"ids":[9]}}
{"id":"1297f505-8175-4951-8461-8ea70045fb44","name":"visible","args":[1,9]}
{"command_id":"1297f505-8175-4951-8461-8ea70045fb44","response":true}
{"id":"12eb3ed2-c6f0-4129-8590-1819ee95fd3c","name":"visible_text","args":[1,9]}
{"command_id":"12eb3ed2-c6f0-4129-8590-1819ee95fd3c","response":" \nPages\nDesign\nFans\nReports\nCommunity\nAccount\nHelp\n View site\n  \nBack\nManage guestbook\nOptions\nNotify me of new posts: Yes\nScreen posts: Yes\nAllow anonymous posts: Yes\nedit display options\n\n \t\nApproval worked\nGuestbook: Manage guestbook\nAll 30\nUnapproved 13\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {10}\nRandom comment #22!\n\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {8}\nRandom comment #24!\n\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {6}\nRandom comment #26!\n\nFirst Prev 1 2\n "}
{"id":"837b7b86-5404-49bb-a1b8-acfa67c113d3","name":"find","args":["xpath","/html"]}
{"command_id":"837b7b86-5404-49bb-a1b8-acfa67c113d3","response":{"page_id":1,"ids":[10]}}
{"id":"0b96e513-6d5c-4a62-9ee8-8c4cea62ee30","name":"visible","args":[1,10]}
{"command_id":"0b96e513-6d5c-4a62-9ee8-8c4cea62ee30","response":true}
{"id":"1133f1aa-eb62-4dd7-a2ca-d5352587c8d1","name":"visible_text","args":[1,10]}
{"command_id":"1133f1aa-eb62-4dd7-a2ca-d5352587c8d1","response":" \nPages\nDesign\nFans\nReports\nCommunity\nAccount\nHelp\n View site\n  \nBack\nManage guestbook\nOptions\nNotify me of new posts: Yes\nScreen posts: Yes\nAllow anonymous posts: Yes\nedit display options\n\n \t\nApproval worked\nGuestbook: Manage guestbook\nAll 30\nUnapproved 13\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {10}\nRandom comment #22!\n\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {8}\nRandom comment #24!\n\nThis comment needs moderation. Approve commentDelete comment\n\nFeb 16, 2:54PMExample Comment {6}\nRandom comment #26!\n\nFirst Prev 1 2\n "}
{"id":"b5b5bd57-749a-4049-b4d9-5d357113195e","name":"execute","args":["console.log('**** Top of All button is at:', $('.all').offset().top)"]}
{"command_id":"b5b5bd57-749a-4049-b4d9-5d357113195e","response":true}
{"id":"5404629c-3bf6-4ef3-9612-777df77deba3","name":"find","args":["xpath",".//a[./@href][(((./@id = 'All' or normalize-space(string(.)) = 'All') or ./@title = 'All') or .//img[./@alt = 'All'])] | .//input[./@type = 'submit' or ./@type = 'reset' or ./@type = 'image' or ./@type = 'button'][((./@id = 'All' or ./@value = 'All') or ./@title = 'All')] | .//input[./@type = 'image'][./@alt = 'All'] | .//button[(((./@id = 'All' or ./@value = 'All') or normalize-space(string(.)) = 'All') or ./@title = 'All')] | .//input[./@type = 'image'][./@alt = 'All']"]}
{"command_id":"5404629c-3bf6-4ef3-9612-777df77deba3","response":{"page_id":1,"ids":[]}}
{"id":"a72335fa-4c6c-4fab-a8e5-cf35e513b618","name":"find","args":["xpath",".//a[./@href][(((./@id = 'All' or contains(normalize-space(string(.)), 'All')) or contains(./@title, 'All')) or .//img[contains(./@alt, 'All')])] | .//input[./@type = 'submit' or ./@type = 'reset' or ./@type = 'image' or ./@type = 'button'][((./@id = 'All' or contains(./@value, 'All')) or contains(./@title, 'All'))] | .//input[./@type = 'image'][contains(./@alt, 'All')] | .//button[(((./@id = 'All' or contains(./@value, 'All')) or contains(normalize-space(string(.)), 'All')) or contains(./@title, 'All'))] | .//input[./@type = 'image'][contains(./@alt, 'All')]"]}
{"command_id":"a72335fa-4c6c-4fab-a8e5-cf35e513b618","response":{"page_id":1,"ids":[11]}}
{"id":"da204f30-1136-4891-9f50-385272ed71db","name":"visible","args":[1,11]}
{"command_id":"da204f30-1136-4891-9f50-385272ed71db","response":true}
{"id":"2710c910-a72b-45d4-aff9-b513ab000e1a","name":"tag_name","args":[1,11]}
{"command_id":"2710c910-a72b-45d4-aff9-b513ab000e1a","response":"A"}
{"id":"e7b409dd-c235-4eca-a1d7-daa4c5b08f2b","name":"click","args":[1,11]}
{"command_id":"e7b409dd-c235-4eca-a1d7-daa4c5b08f2b","error":{"name":"Poltergeist.MouseEventFailed","args":["click","html.js.flexbox.flexboxlegacy.canvas.canvastext.no-touch.postmessage.websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.cssvhunit.fileinput.cssvwunit.no-highresdisplay.no-ios.no-ie.js.no-flexbox.flexboxlegacy.canvas.canvastext.touch.postmessage.websqldatabase.no-indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.cssreflections.csstransforms.no-csstransforms3d.csstransitions.fontface.generatedcontent.no-video.no-audio.localstorage.sessionstorage.webworkers.applicationcache.no-cssvhunit.fileinput.no-cssvwunit.no-highresdisplay.no-ios.no-ie body#guestbook.bz.options.with_sidebar.with-navigation.pro-feature-access.no-alert.livechat-offline div#controlpanel-container header#page-header.bz.mode-controlpanel div.header-container nav#navigation.clearfix",{"x":846.5,"y":26}]}}
{"id":"7abc575e-79a1-440e-9183-855f8d2c93a7","name":"render","args":["/Users/work/poltergeist/capybara-201602171724209395958211.png",false,null]}
{"command_id":"7abc575e-79a1-440e-9183-855f8d2c93a7","response":true}
{"id":"093bb379-7438-45c5-a4b7-9ae708b81222","name":"reset","args":[]}
{"command_id":"093bb379-7438-45c5-a4b7-9ae708b81222","response":true}
F

Failures:

  1) Capybara::Poltergeist::Driver works
     Failure/Error: raise MouseEventFailed.new(self, error.response)

     Capybara::Poltergeist::MouseEventFailed:
       Firing a click at co-ordinates [846.5, 26] failed. Poltergeist detected another element with CSS selector 'html.js.flexbox.flexboxlegacy.canvas.canvastext.no-touch.postmessage.websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.cssvhunit.fileinput.cssvwunit.no-highresdisplay.no-ios.no-ie.js.no-flexbox.flexboxlegacy.canvas.canvastext.touch.postmessage.websqldatabase.no-indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.cssreflections.csstransforms.no-csstransforms3d.csstransitions.fontface.generatedcontent.no-video.no-audio.localstorage.sessionstorage.webworkers.applicationcache.no-cssvhunit.fileinput.no-cssvwunit.no-highresdisplay.no-ios.no-ie body#guestbook.bz.options.with_sidebar.with-navigation.pro-feature-access.no-alert.livechat-offline div#controlpanel-container header#page-header.bz.mode-controlpanel div.header-container nav#navigation.clearfix' at this position. It may be overlapping the element you are trying to interact with. If you don't care about overlapping elements, try using node.trigger('click').
     # ./lib/capybara/poltergeist/node.rb:23:in `rescue in command'
     # ./lib/capybara/poltergeist/node.rb:17:in `command'
     # ./lib/capybara/poltergeist/node.rb:131:in `click'
     # /Users/work/.rvm/gems/ruby-2.1.2/gems/capybara-2.6.2/lib/capybara/node/element.rb:134:in `block in click'
     # /Users/work/.rvm/gems/ruby-2.1.2/gems/capybara-2.6.2/lib/capybara/node/base.rb:84:in `synchronize'
     # /Users/work/.rvm/gems/ruby-2.1.2/gems/capybara-2.6.2/lib/capybara/node/element.rb:134:in `click'
     # /Users/work/.rvm/gems/ruby-2.1.2/gems/capybara-2.6.2/lib/capybara/node/actions.rb:13:in `click_link_or_button'
     # /Users/work/.rvm/gems/ruby-2.1.2/gems/capybara-2.6.2/lib/capybara/session.rb:686:in `block (2 levels) in <class:Session>'
     # ./spec/integration/bz_spec.rb:47:in `block (2 levels) in <module:Poltergeist>'
     # ------------------
     # --- Caused by: ---
     # Capybara::Poltergeist::BrowserError:
     #   There was an error inside the PhantomJS portion of Poltergeist. If this is the error returned, and not the cause of a more detailed error response, this is probably a bug, so please report it. 
     #   
     #   Poltergeist.MouseEventFailed: click
     #   html.js.flexbox.flexboxlegacy.canvas.canvastext.no-touch.postmessage.websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.cssvhunit.fileinput.cssvwunit.no-highresdisplay.no-ios.no-ie.js.no-flexbox.flexboxlegacy.canvas.canvastext.touch.postmessage.websqldatabase.no-indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.cssreflections.csstransforms.no-csstransforms3d.csstransitions.fontface.generatedcontent.no-video.no-audio.localstorage.sessionstorage.webworkers.applicationcache.no-cssvhunit.fileinput.no-cssvwunit.no-highresdisplay.no-ios.no-ie body#guestbook.bz.options.with_sidebar.with-navigation.pro-feature-access.no-alert.livechat-offline div#controlpanel-container header#page-header.bz.mode-controlpanel div.header-container nav#navigation.clearfix
     #   {"x"=>846.5, "y"=>26}
     #   ./lib/capybara/poltergeist/browser.rb:351:in `command'

Deprecation Warnings:

Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from /Users/work/poltergeist/spec/integration/bz_spec.rb:27:in `block (2 levels) in <module:Poltergeist>'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

1 deprecation warning total

Finished in 13.02 seconds (files took 1.14 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/integration/bz_spec.rb:21 # Capybara::Poltergeist::Driver works
```

**Comment by twalpole** [comment] 2016-02-17 23:42
What version of phantomjs are you running this with?  I checked out your repo and attempted to run the test you have logged above and the test fails with a 'Facebook Pixel Error: Pixel code is not installed correctly on this page' javascript error -  If I disable js_errors then it fails on line 29 attempting to click '#comment_1599 .interaction_link.destroy_link i' due to overlapping elements

**Comment by marcandre** [comment] 2016-02-18 00:16
Thanks for checking it out.

Mmm, I assumed I was using the latest `phantom_js`, but it was v1.9.7.

Let me check with 2.1.1 and come back to you.

**Comment by twalpole** [comment] 2016-02-18 00:19
Ok -- the initial click is failing for me because the width of the ''#comment_1599 .interaction_link.destroy_link i' is 0  -- I think thats because resources are missing

**Comment by marcandre** [comment] 2016-02-18 00:22
Ok, updated my branch by nuking the facebook thing and clicking on the big "Delete Comment" button instead of small icon that created an issue (both have same effect).

Symptoms appear to be the same, in particular that taking a screenshot alleviates the problem...

Looks like `phantomjs` 2.2 is out, but `brew` doesn't have a recipe yet. If that's the version you have, let me know if you can't reproduce the issue and I'll try installing it somehow.

**Comment by twalpole** [comment] 2016-02-18 01:07
I'm using 2.1.1 and am seeing the issue now. getBoundingClientRect() on the element is reporting top: -6 and bottom 26.59  - the page is scrolled a bit and the element is partially off the top -- but it scrolls again when going to click the element and the click is then at the wrong position -- as a workaround I added    @session.current_window.resize_to(1920,4000)  in the before section of your test which means no scrolling is needed in your test and then it passes

**Comment by twalpole** [comment] 2016-02-18 01:17
FYI -- I don't think 2.2 is out -- the issue to release it is still open - https://github.com/ariya/phantomjs/issues/13937  -  Also, thanks a lot for creating a reproducible test, it makes working on things much nicer.

**Comment by twalpole** [comment] 2016-02-18 02:03
Ok -- so it's not that the element is scrolling after we've calculated its position - The issue is the way the page has been scrolled, the elment you're trying to click is sitting under the header - I'm not sure what if s anything poltergeist can do about that.  I don't think we want to be trying to randomly scroll the page around every time an element overlaps

**Comment by twalpole** [comment] 2016-02-18 02:25
@marcandre  After all that your test basically boils down to

    it 'works' do
      @session.visit('/controlpanel/bz')

      @session.execute_script 'window.scrollTo(0,150)'
      @session.click_on 'All'
    end

**Comment by twalpole** [comment] 2016-02-18 02:25
I'm going to close this since the error thats being reported is correct -- the element is overlapped.

**Closed by twalpole** 2016-02-18 02:25 UTC

**Comment by marcandre** [comment] 2016-02-18 06:44
lol, I see... The header is overlapping with some specific scrolling values.

First, thanks for checking this so quickly.

I would venture that there are a couple of bugs / feature requests in there, though.

1) Shouldn't the screenshot reflect the current viewport *including the way it is scrolled*?

2) Shouldn't taking a screenshot not affect a spec in any way?

I imagine that screenshotting somehow scrolls to the top, but that both hides problems like this one and create eisenbugs...

3) Could Poltergeist try to avoid situations like this by scrolling? Say an element we want to click is in the viewport but overlapped. If there are scrollbars, it would be easy to scroll that element towards the center and try again. Only raise an error if the element is still overlaped. I mean it's nice that poltergeist takes responsibility for scrolling the page, but ideally it would take it fully in a robust manner. 

In the current situation, I can imagine some specs that were passing suddenly fail because the header's dimension has changed, or the CSS for any of the elements on the page (which happen to push a given button slightly offscreen, or just requiring a different scroll value for some other button to appear in the view), or changing the viewport dimension, etc...

**Comment by twalpole** [comment] 2016-02-18 18:01
@marcandre  In response to each of your points

1) That sounds like a good idea, and it might be worth at least having an option that would select that behavior (like the full and selector   The current implementation starts [here](https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/client/browser.coffee#L362)  and does scroll to the top before calling the PhantomJS render on the current page, and then attempts to scroll back to where it was.  I did a quick test and commented out everything other than calling PhantomJS render and the result ending up being the same so it appears PhantomJS is probably scrolling to the top which would mean this can't be done currently :(

2)  Yes that would be great, and the implementation I linked to in 1 does attempt to reset to scroll to the original position -- looks like maybe there's a bug there

3)  It could, but what algorithm would be good for this - would it scroll horizontally and vertically to try and find a place on the page the element is clickable?  Should it only do it if the element overlapping has position: fixed, etc, etc..  I don't think it's possible to do this in a "fully robust" manner that also does not become ridiculously slow.  It may be possible to do something like scroll down by the document top padding if a click fails because the element under a position:fixed element just to push elements out from under a fixed header but that is getting pretty hacky -- a better solution may just be to set your default page height longer so scrolling during tests isn't necessary

**Comment by marcandre** [comment] 2016-02-18 19:47
1) Thanks. I was able to get the right screenshot by commenting out the code *and* using `@driver.scroll_to 0, 150` instead of `execute_script 'window.scrollTo`. I found that out because otherwise `scrollPosition().top` is 0 on the JS side.

I'm not sure I understand everything, but isn't is a bug that `phantomjs` behaves differently with `page.setScrollPosition` and `window.scrollTo`? Or what am I missing?

2) See above; `scrollPosition()` returns 0 although that seems to be incorrect. So when you reset the scroll, you are then resetting it to that incorrect value...

3) I agree that trying to detect the dimensions of whatever is overlapping and trying to clear it would be complex.
I think a simple algorithm would be if we assume that fixed elements would be on the border of the viewport. We simply need to scroll horizontally and vertically once to make center of desired object as close as possible to center of viewport. This would be in addition to your current "minimal" scrolling if the object is outside of viewport, and would happen only if object is overlapped.
I think speed would be a non issue with this algorithm, since it would only impact either actual spec failures, or those rare cases where we actually need the scrolling to happen.

**Comment by twalpole** [comment] 2016-02-23 19:11
1)  It sounds like a bug that window.scrollTo and scrollPosition behave differently, although I haven't really looked into it - If it is it would need to be taken up with the phantomJS project.

2)  It's based off validatedDimensions which is a workaround for https://github.com/ariya/phantomjs/issues/10277 - when I have a few minutes I'll take a look,  I don't think we care about validatedDimensions in this case since we just want the previous scroll position to restore

3) Ok- but then this still wouldn't be robust, so how far is it worth taking it?

**Comment by marcandre** [comment] 2016-02-23 19:27
2) Just to be clear, it's all due to point 1). We get 0 if we called `window.scrollTo` and 150 if we called `setScrollPosition` instead.

3) It's only my opinion, but if there's a fixed element in the center of the screen (dialog box? alert box? publicity?), then it won't be clear to a user how to scroll to have anything appear, so it's ok if the spec fails. If the fixed elements are sidebars, a footer or a header, it will be clear for the user to scroll to have an element be available, so the spec shouldn't fail. In that sense, it would be robust. If it's not overly complicated, I'd recommend to implement it; you'll see if someone else opens an issue :smile:
Would you like a PR for this?

**Comment by twalpole** [comment] 2016-02-23 20:04
3) Sure -- PRs are always considered :)

**Comment by twalpole** [comment] 2016-02-23 22:36
@marcandre For #1/#2 it seems like there are actually two different scrolling contexts -- one scrolls the phantomjs view of the page, the other actually scrolls in the window -- I've pushed branch render_scroll  -- see if that is now doing what you would expect as far as taking a screenshot not affecting your test behavior.

**Comment by marcandre** [comment] 2016-02-23 23:03
I don't understand the two contexts, but I'll have a look at the branch. I'll be travelling in the next weeks, not sure to have much time.

**Comment by twalpole** [comment] 2016-02-23 23:08
@marcandre Yeah - not sure I fully understand the two contexts either - it just appears they both scroll independently, and thanks :)
