### ISSUE TITLE
Is there an option to optionally ignore the window size?

### ISSUE THREAD

**Issue by NullVoxPopuli** [teampoltergeist/poltergeist#620] opened 2015-05-06 22:01 UTC
Testing various window sizes is great, but I'd like to have an option to disable that for certain tests, or have it globally disabled, and then specify which tests have it enabled. 

I've currently worked around this my setting my window size to something large. But in the event there is still a scroll issue, I'd like it to be able to just click things that exist on the page. 
(this is the default for capybara-webkit)

**Comment by route** [comment] 2015-05-07 06:50
I didn't get the point of this whole

**Comment by route** [comment] 2015-05-10 09:54
Can you describe your concrete case?

**Comment by NullVoxPopuli** [comment] 2015-05-10 11:15
in my case, you'd have to scroll to get to something. But I want to be able to have the headless browser not scroll at all to be able to click on things that aren't in the current view port

**Comment by twalpole** [comment] 2015-10-29 17:07
clicking on items scrolls them into view before clicking on them if needed, so I'm not really sure what the issue is.  I'm going to close this for now - if there is a concrete use case that doesn't work with the automatic scroll into view functionality please provide an example and we can reopen

**Closed by twalpole** 2015-10-29 17:07 UTC
