### ISSUE TITLE
False positives on checkbox click (includes test case)

### ISSUE THREAD

**Issue by jpurcell001** [teampoltergeist/poltergeist#280] opened 2013-03-18 20:34 UTC
We are seeing intermittent failures when trying to click a checkbox.  Symptoms sound very similar to #120 - Capybara/Poltergeist acts like the click was successful, but it seemed to have clicked in the wrong spot.  In our case we have a form that has options shown/hidden (no animations, just hide/show) depending on other choices, and it seems like there's some sort of a race condition where, intermittently, Poltergeist just misses the checkbox.

Put together a gist that seems to reproduce the problem.  Generally fails within the first 10 iterations for me, often even earlier, but it seems to be a timing thing so you might have to play with the delays a bit.

https://gist.github.com/jpurcell001/5190514

This is using master of capybara/xpath as well as master of poltergeist.

The same gist passes without issue when using either selenium or webkit, so it feels like a poltergeist-specific issue.

**Comment by twalpole** [comment] 2015-11-12 01:17
This would seem to be a duplicate of #286 so I'm going to close this one - as a potential solution - rather than switching to trigger(:click) when you know your checkboxes will hide rows you can use
   
     #click the checkbox
     expect(page).not_to have_selector(:css, 'css selector of the element that should be hidden')
    #click the next checkbox

This will have the effect of testing that your rows do hide as you expect, and also making the test wait until the page is stable to click the next checkbox

**Closed** 2015-11-12 01:18 UTC

**Comment by jpurcell001** [comment] 2015-11-12 01:24
No problem @twalpole.   Hopefully the test case / gist is still helpful in resolving #286.
