### ISSUE TITLE
Problems with redirect to HTTPS

### ISSUE THREAD

**Issue by andrewhavens** [teampoltergeist/poltergeist#121] opened 2012-07-26 16:10 UTC
I have a cucumber test suite using Capybara and Selenium which is all passing. I'm trying to switch to Poltergeist to speed up my tests, however I'm having problems getting it to work.

The first step of my test is to go to the login page and log in, but it's failing. The browser should first navigate to the insecure `http://dev.example.com/auth/login`, then redirect to the secure `https://dev.myapp.com/auth/login`. We are using self-signed certificates, but I enabled `ignore-ssl-errors` and it's still failing:

    # in my env.rb
    Capybara.register_driver :poltergeist do |app|
      Capybara::Poltergeist::Driver.new(app, debug: true, phantomjs_options: ['--ignore-ssl-errors=yes', '--local-to-remote-url-access=yes'])
    end

    # output of running test
    {"name"=>"visit", "args"=>["http://dev.myapp.com/auth/login"]}
    {"response"=>"fail"}
    {"name"=>"find", "args"=>[".//*[@id = 'login']"]}
    {"response"=>{"page_id"=>0, "ids"=>[]}}
    ...and so on

What do I need to do to get this working?

**Comment by 0xCCD** [comment] 2015-02-10 21:48
thx @dmacvicar

**Comment by ollyjshaw** [comment] 2015-08-26 14:56
:+1: @dmacvicar thanks!

**Comment by twalpole** [comment] 2015-11-13 22:04
Closing since this seems to have been an SSL settings issue -- we can reopen/open a new issue if people are still having problems

**Closed** 2015-11-13 22:11 UTC
Labels: bug

**Comment by luismsilva99** [comment] 2016-11-16 14:35
Faced the same problem with poltergeist 1.3.0, capybara 1.9.1 and capybara 2.1.0 .
Solved with
```
Capybara.register_driver :poltergeist do |app|
  options = {:phantomjs_options => ['--ignore-ssl-errors=yes', '--ssl-protocol=any']}

  Capybara::Poltergeist::Driver.new(app, options)
end
```

**Comment by x-yuri** [comment] 2017-03-13 01:31
I'm doing web scraping, and `--ssl-protocol=any` helped me.

**Comment by michaelschmitz** [comment] 2018-06-09 18:47
Same situation as x-yuri and luismsilva99. Many pages would work fine, some would not load at all.

**Comment by twalpole** [comment] 2018-06-09 19:40
@michaelschmitz This was closed over 2 years ago due to being user setting issues.  If you actually have found a bug in Poltergeist please open a new issue and provide a reproducible example.
