### ISSUE TITLE
page.evaluate_script - memory leak

### ISSUE THREAD

**Issue by ahorek** [teampoltergeist/poltergeist#845] opened 2017-01-18 20:40 UTC
# current behaviour

executing command
**page.evaluate_script("$('#element').attr('readOnly', false);")**

2,4 GB of memory is allocated to handle the response which is later garbage collected

## output
=> {"0"=>
  {"ALLOW_KEYBOARD_INPUT"=>1,
   "ATTRIBUTE_NODE"=>2,
   "CDATA_SECTION_NODE"=>4,
   "COMMENT_NODE"=>8,
   "DOCUMENT_FRAGMENT_NODE"=>11,
   "DOCUMENT_NODE"=>9,
   "DOCUMENT_POSITION_CONTAINED_BY"=>16,
   "DOCUMENT_POSITION_CONTAINS"=>8,
   "DOCUMENT_POSITION_DISCONNECTED"=>1,
   "DOCUMENT_POSITION_FOLLOWING"=>4,
   "DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC"=>32,
   "DOCUMENT_POSITION_PRECEDING"=>2,
   "DOCUMENT_TYPE_NODE"=>10,
   "ELEMENT_NODE"=>1,
   "ENTITY_NODE"=>6,
   "ENTITY_REFERENCE_NODE"=>5,
   "NOTATION_NODE"=>12,
   "PROCESSING_INSTRUCTION_NODE"=>7,
   "TEXT_NODE"=>3,
   "accessKey"=>"",
   "addEventListener"=>nil,
   "appendChild"=>nil,
   "attributes"=>
    {"0"=>
      {"ATTRIBUTE_NODE"=>2,
       "CDATA_SECTION_NODE"=>4,
       "COMMENT_NODE"=>8,
       "DOCUMENT_FRAGMENT_NODE"=>11,
       "DOCUMENT_NODE"=>9,
       "DOCUMENT_POSITION_CONTAINED_BY"=>16,
       "DOCUMENT_POSITION_CONTAINS"=>8,
       "DOCUMENT_POSITION_DISCONNECTED"=>1,
       "DOCUMENT_POSITION_FOLLOWING"=>4,
       "DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC"=>32,
       "DOCUMENT_POSITION_PRECEDING"=>2,
       "DOCUMENT_TYPE_NODE"=>10,
       "ELEMENT_NODE"=>1,
       "ENTITY_NODE"=>6,
       "ENTITY_REFERENCE_NODE"=>5,
       "NOTATION_NODE"=>12,
       "PROCESSING_INSTRUCTION_NODE"=>7,
       "TEXT_NODE"=>3,
       "addEventListener"=>nil,
       "appendChild"=>nil,
       "baseURI"=>"",
       "childNodes"=>{"0"=>nil, "item"=>nil, "length"=>1},
       "cloneNode"=>nil,
       "compareDocumentPosition"=>nil,
       "contains"=>nil,
       "dispatchEvent"=>nil,
       "firstChild"=>nil,
       "hasChildNodes"=>nil,
       "insertBefore"=>nil,
       "isDefaultNamespace"=>nil,
       "isEqualNode"=>nil,
       "isId"=>false,
       "isSameNode"=>nil,
       "isSupported"=>nil,
       "lastChild"=>
....

## memory profile
Total allocated: 2402785110 bytes (13043018 objects)
Total retained:  40 bytes (1 objects)

allocated memory by gem
-----------------------------------
1791150583  json-1.8.6
 541769990  websocket-driver-0.6.4
  69833290  poltergeist-1.12.0
     30158  Ruby22-x64/lib
       520  activesupport-4.2.7.1
       280  websocket-extensions-0.1.2
       209  capybara-2.11.0
        80  other

allocated memory by file
-----------------------------------
1791150583  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/json-1.8.6/lib/json/common.rb
 436911712  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/websocket-driver-0.6.4/lib/websocket/driver/hybi.rb
  69832530  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/poltergeist-1.12.0/lib/capybara/poltergeist/web_socket_server.rb
  52429079  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/websocket-driver-0.6.4/lib/websocket/driver/stream_reader.rb
  52428959  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/websocket-driver-0.6.4/lib/websocket/driver/hybi/message.rb
      7278  c:/Ruby22-x64/lib/ruby/2.1.0/webrick/httpresponse.rb
      6888  c:/Ruby22-x64/lib/ruby/2.1.0/webrick/utils.rb
      5208  c:/Ruby22-x64/lib/ruby/2.1.0/webrick/htmlutils.rb
      4168  c:/Ruby22-x64/lib/ruby/2.1.0/webrick/httpserver.rb
      2856  c:/Ruby22-x64/lib/ruby/2.1.0/webrick/log.rb

allocated memory by location
-----------------------------------
1791148589  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/json-1.8.6/lib/json/common.rb:155
 388362584  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/websocket-driver-0.6.4/lib/websocket/driver/hybi.rb:340
  52429039  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/websocket-driver-0.6.4/lib/websocket/driver/stream_reader.rb:22
  52428959  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/websocket-driver-0.6.4/lib/websocket/driver/hybi/message.rb:17
  50489520  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/poltergeist-1.12.0/lib/capybara/poltergeist/web_socket_server.rb:80
  48545359  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/websocket-driver-0.6.4/lib/websocket/driver/hybi.rb:338
  13274240  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/poltergeist-1.12.0/lib/capybara/poltergeist/web_socket_server.rb:79
   6068224  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/poltergeist-1.12.0/lib/capybara/poltergeist/web_socket_server.rb:76
      5248  c:/Ruby22-x64/lib/ruby/2.1.0/webrick/utils.rb:167
      2920  c:/Ruby22-x64/lib/ruby/2.1.0/webrick/httpserver.rb:75

allocated memory by class
-----------------------------------
1771286238  String
 401672728  Array
 223744128  Hash
   6074368  Time
      2336  JSON::Ext::Parser
      1680  MatchData
      1480  Bignum
       768  Thread::Backtrace
       416  JSON::Ext::Generator::State
       248  WebSocket::Driver::Hybi::Frame

allocated objects by gem
-----------------------------------
  12615844  json-1.8.6
    426686  poltergeist-1.12.0
       431  Ruby22-x64/lib
        36  websocket-driver-0.6.4
        13  activesupport-4.2.7.1
         4  capybara-2.11.0
         2  other
         2  websocket-extensions-0.1.2

allocated objects by file
-----------------------------------
  12615844  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/json-1.8.6/lib/json/common.rb
    426677  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/poltergeist-1.12.0/lib/capybara/poltergeist/web_socket_server.rb
       120  c:/Ruby22-x64/lib/ruby/2.1.0/webrick/htmlutils.rb
        91  c:/Ruby22-x64/lib/ruby/2.1.0/webrick/httpserver.rb
        82  c:/Ruby22-x64/lib/ruby/2.1.0/webrick/utils.rb
        48  c:/Ruby22-x64/lib/ruby/2.1.0/webrick/httpresponse.rb
        36  c:/Ruby22-x64/lib/ruby/2.1.0/webrick/log.rb
        30  c:/Ruby22-x64/lib/ruby/2.1.0/webrick/httpversion.rb
        19  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/websocket-driver-0.6.4/lib/websocket/driver/hybi.rb
        13  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb

allocated objects by location
-----------------------------------
  12615820  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/json-1.8.6/lib/json/common.rb:155
    331856  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/poltergeist-1.12.0/lib/capybara/poltergeist/web_socket_server.rb:79
     47408  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/poltergeist-1.12.0/lib/capybara/poltergeist/web_socket_server.rb:76
     47408  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/poltergeist-1.12.0/lib/capybara/poltergeist/web_socket_server.rb:80
        73  c:/Ruby22-x64/lib/ruby/2.1.0/webrick/httpserver.rb:75
        41  c:/Ruby22-x64/lib/ruby/2.1.0/webrick/utils.rb:167
        41  c:/Ruby22-x64/lib/ruby/2.1.0/webrick/utils.rb:168
        24  c:/Ruby22-x64/lib/ruby/2.1.0/webrick/htmlutils.rb:19
        24  c:/Ruby22-x64/lib/ruby/2.1.0/webrick/htmlutils.rb:20
        24  c:/Ruby22-x64/lib/ruby/2.1.0/webrick/htmlutils.rb:21

allocated objects by class
-----------------------------------
  12628320  String
    332428  Array
     47456  Time
     34743  Hash
        37  Bignum
         6  MatchData
         6  Thread::Backtrace
         6  WEBrick::HTTPStatus::EOFError
         6  WEBrick::HTTPVersion
         2  JSON::Ext::Generator::State

retained memory by gem
-----------------------------------
        40  websocket-driver-0.6.4

retained memory by file
-----------------------------------
        40  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/websocket-driver-0.6.4/lib/websocket/driver/stream_reader.rb

retained memory by location
-----------------------------------
        40  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/websocket-driver-0.6.4/lib/websocket/driver/stream_reader.rb:47

retained memory by class
-----------------------------------
        40  String

retained objects by gem
-----------------------------------
         1  websocket-driver-0.6.4

retained objects by file
-----------------------------------
         1  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/websocket-driver-0.6.4/lib/websocket/driver/stream_reader.rb

retained objects by location
-----------------------------------
         1  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/websocket-driver-0.6.4/lib/websocket/driver/stream_reader.rb:47

retained objects by class
-----------------------------------
         1  String

Allocated String Report
-----------------------------------
   3732901  ""
   3732896  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/json-1.8.6/lib/json/common.rb:155
         3  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/websocket-driver-0.6.4/lib/websocket/driver/hybi/message.rb:17
         1  (pry):2
         1  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/websocket-driver-0.6.4/lib/websocket/driver/stream_reader.rb:47

     37168  "cssText"
     37168  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/json-1.8.6/lib/json/common.rb:155

     37168  "parentRule"
     37168  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/json-1.8.6/lib/json/common.rb:155

     34000  "length"
     34000  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/json-1.8.6/lib/json/common.rb:155

     30392  "item"
     30392  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/json-1.8.6/lib/json/common.rb:155

     24508  "0"
     24508  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/json-1.8.6/lib/json/common.rb:155

     20246  "height"
     20246  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/json-1.8.6/lib/json/common.rb:155

     20068  "width"
     20068  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/json-1.8.6/lib/json/common.rb:155

     19962  "type"
     19962  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/json-1.8.6/lib/json/common.rb:155

     19804  "position"
     19804  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/json-1.8.6/lib/json/common.rb:155

Retained String Report
-----------------------------------
         1  ""
         1  c:/Ruby22-x64/lib/ruby/gems/2.1.0/gems/websocket-driver-0.6.4/lib/websocket/driver/stream_reader.rb:47

# expected behaviour
works well with execute_script which doesn't include the response
page.execute_script("$('#element').attr('readOnly', false);")

or with chrome driver
output
page.evaluate_script("$('#element').attr('readOnly', false);")
=> [#<Selenium::WebDriver::Element:0x..fd7718466 id="0.8665422464040573-2">]

no extra memory is allocated

## platform
Windows 10
Ruby 2.1.5 x64
Poltergeist 1.12.0
Phantomjs 2.1.1 (same issue with 2.5 beta)

**Comment by twalpole** [comment] 2017-01-18 21:04
If this is getting garbage collected it's not leaking.  Why are you calling `evaluate_script` if you don't want the result? - that's exactly what execute_script is for.

**Comment by twalpole** [comment] 2017-01-18 21:13
Closing since this is expected behavior -  `evaluate_script` is returning a JSON representation of the JQuery object returned by `attr` - If you don't want the result you should be calling `execute_script` as documented in Capybara

**Closed by twalpole** 2017-01-18 21:13 UTC

**Comment by ahorek** [comment] 2017-01-18 21:37
@twalpole I was expecting an output like this without extra memory footprint
=> [#<Selenium::WebDriver::Element:0x..fd7718466 id="0.8665422464040573-2">]

but I agree evaluate_script shouldn't be used this way. My mistake. Thanks for the explanation.
