### ISSUE TITLE
Failures only for poltergeist

### ISSUE THREAD

**Issue by danielb2** [teampoltergeist/poltergeist#360] opened 2013-07-23 02:00 UTC
Hi, I've got tests which work fine with selenium driver and webkit driver. However, since I can't get webkit compiled on the TI server, and it's headless, I need to have poltergeist working.

Here's an example test:

``` ruby
                                                                                                                  
 it "should skip member page after selecting a school if already signed in", js: true do                  
   visit eboxtops_signup_path                                                                                     
   school = FactoryGirl.create :school                                                                            
   fill_in :find_my_school, with: "ABC elementary"                                                                
   click_button 'search-btn'                                                                                      
   click_link 'ABC Elementary School'                                                                             
   page.should_not have_content 'Are you a member?'                                                       
 end                                                                                                              
```

The error I get, repeatedly, is:

```
 1) Eboxtop integration should skip member page after selecting a school if already signed in
    Failure/Error: fill_in :find_my_school, with: "ABC elementary"
    Capybara::ElementNotFound:
      Unable to find field :find_my_school
```

I should note that I don't always get the same error, sometimes I get other errors. Sometimes I don't get this error, but I always get an error with poltergeist.

I don't really know what to do to debug this since it works elsewhere. 

Maybe we can work together to figure out what the discrepancy is here?

**Comment by twalpole** [comment] 2015-11-14 20:55
Closing this to being over 2 years old and lots of changes in poltergeist since then.  If this is still a valid issue with a current poltergeist version we can reopen

**Closed by twalpole** 2015-11-14 20:55 UTC

**Comment by vinpereira** [comment] 2016-11-25 15:42
Hi there,

I have the same problem with the following versions:

- poltergeist (1.11.0)
- capybara (2.10.1, 2.7.1)
- selenium-webdriver (3.0.1)
- cucumber (2.4.0)

I use the following code to match two buttons and one link:
`Given (/^I press "(.*)"$/) do |button_name|
  click_link_or_button("#{button_name}")
end`

It works fine with Selenium. But when I try to use Poltergeist, it fails when try to click in the link.
Unable to find link or button "..." (Capybara::ElementNotFound).

Any help, please?

**Comment by simi** [comment] 2016-11-25 15:53
@vinpereira can you inspect the page body before this error occurs if you'll be able to find target element there?

**Comment by twalpole** [comment] 2016-11-25 15:54
What version of PhantomJS are you using? And have you use save_and_open_page to see what HTML poltergeist is seeing?

**Comment by vinpereira** [comment] 2016-11-25 16:29
@simi I tried the inspect but it's a lot of info, so I got lost...
@twalpole It's PhantomJS 2.1.1 at Windows 10.

I used the capybara-screenshoot to capture a picture on every failure and I notice this:

- Before the click_link_or_button the following code is called:
`if find(:id, 'showTimelineTable').visible?
    find(:id, 'showTimelineTable').click
  end`

- The code above check is the TimelineTable button is visible. If it's, then the Table is not visible. So I press the button to change to the Table
- Then with the Table visible, I could click_link... where the problem is.
- The poltergeist says that OK the if block, but it actually does not perform the find(:id, 'showTimelineTable').click. So the click_link "problem" is right, there is nothing to click.

**Comment by vinpereira** [comment] 2016-11-25 16:46
I added an expectation to the code, but the problem still happens:
`element = find(:id, 'showTimelineTable')
  if element.visible?
    element.click
  end
  expect(page).to have_xpath('//a[@id="showTimeline"]')`

Again, if the TimelineTable button is visible, then the Table is not visible. So I click the button to "open it". When I do this, the Timeline button (not the Table version) appears, so I could change back.

By doing this, I noticed that the button change but the Table is not loaded yet when the next step is performed. So I believe the problem is not at Poltergeistbut at PhantomJS.

Maybe a sleep or wait is required?

**Comment by twalpole** [comment] 2016-11-25 17:55
@vinpereira Have you set Capybara.ignore_hidden_elements = false (highly not recommended for testing web apps) ?  If not your code doesn't really make any sense.  

Since you say you click the button but the table doesn't appear I'm guessing you have JS errors in your page (enable js_errors in your driver registration - https://github.com/teampoltergeist/poltergeist#customization ) possibly caused by using ES2015 methods or syntax which PhantomJS does not support.

**Comment by vinpereira** [comment] 2016-11-25 17:59
@twalpole I did not set to false. Will not? I don't know if helps, but it's a SPA.

The app is a BPMS so it's not "my code" and I'm trying to test a process execution. I needed to put :js_errors to false.

**Comment by twalpole** [comment] 2016-11-25 18:16
So since it's not set to false - find will only find visible elements, so finding and then checking if visible is pointless.  For your conditional you'd want to do something like

    if page.has_css?('#showTimelineTable)
        page.find('#showTimelineTable).click # click_link or click_button would be better but I don't what showTimelineTable actually is
    end

Beyond that, if you can't run with js_errors: true then you have no easy way of figuring out why the click isn't triggering the show of the table

**Comment by vinpereira** [comment] 2016-11-25 18:18
@twalpole Thanks!! I will try to find and fix all JS errors in this scenario.

**Comment by vinpereira** [comment] 2016-11-25 18:34
@twalpole The 'showTimelineTable' has a 'display: block'. When I click it, it changes to 'display: none' and the other one ('showTimeline') do the reverse.

That's why I checked for visible

**Comment by twalpole** [comment] 2016-11-25 19:44
@vinpereira But `find` (by default) will only return visible elements (it raises an exception if there is no matching visible element), so checking if a returned element is visible is pointless - if it was returned it is visible (unless you've changed the default setting for ignore_hidden_elements or are passing a `:visible` option to the find)

**Comment by vinpereira** [comment] 2016-11-29 19:16
@twalpole Thanks!! I got it!
