### ISSUE TITLE
Tests with phantomjs - sometimes green sometimes red.

### ISSUE THREAD

**Issue by panSarin** [teampoltergeist/poltergeist#340] opened 2013-06-12 11:25 UTC
About 50% times when i run my test it return ok, but in other 50% times it is failure.
Sometimes with: 

```
     Failure/Error: click_button 'Lorem'
     Capybara::Poltergeist::DeadClient:
       PhantomJS client died while processing {"name":"click","args":[3,3]}
```
and sometimes even earlier with:

```
     Failure/Error: visit some_path(@some.id)
     Capybara::Poltergeist::DeadClient:
       PhantomJS client died while processing {"name":"visit","args":["http://localhost:54544/some_path/4"]}
```

Any ideas?

**Comment by karolxavierleite** [comment] 2015-01-06 19:37
+1 

I'm having the same problem. I'm using poltergeist with Capybara.

My versions:
poltergeist: 1.5.0
phantomJS: 1.9.7
capybara: 2.2.1

**Comment by cassioscabral** [comment] 2015-01-23 21:40
+1

I'm having the same problem. I'm using poltergeist with Capybara.

My versions:
poltergeist: 1.4.1
phantomJS: 1.9.8
capybara: 2.1.0

**Comment by pahlawat** [comment] 2015-02-13 14:32
+1
Having same issue, tests run locally but not running on CI

**Comment by khaidpham** [comment] 2015-03-25 05:01
+1
Was having the same issue with poltergeist 1.5.1 and phantomJS 1.9.8, phantomJS crashed when visit() certain sites with some js errors
However, after uninstalling phantomJS 1.9.8 and install the latest phantomJS 2.0, visiting the same sites no longer crash phamtomJS

**Comment by hamza88** [comment] 2015-07-28 15:34
Tried downgrading to Phantomjs to 1.9.8 whilst using capybara 2.2.1 and Poltergeist 1.5.1 ... no luck. Have experimented with versions. 

Still getting inconsistent results ...

**Comment by HeroicAutodidact** [comment] 2015-08-13 00:59
I upgraded to PhantomJS 2.0 (compiled from source on Ubuntu) and it finally works! Tried six other version combinations with no luck. I am sometimes getting a 'Timeout Error'. Will continue experimenting with other versions of Capybara and Poltergeist. 

Capybara 2.4.4
Poltergeist 1.6.0
PhantomJS 2.0.0

**Comment by Dfenniak** [comment] 2015-08-31 00:27
I have the exact versions mentioned above and I'm still seeing the issue.

**Comment by twalpole** [comment] 2015-11-16 06:32
I'm closing this due to the age of the original issue and the fact no one has actually posted any real details about the issues or a reproducible test case -  If anyone is having actual issues, please open a new issue with real details about all versions used, details of the tests that are failing, and if possible a reproducible minimal test case

**Closed by twalpole** 2015-11-16 06:32 UTC
