### ISSUE TITLE
Capybara::Poltergeist::TimeoutError

### ISSUE THREAD

**Issue by dlandberg** [teampoltergeist/poltergeist#375] opened 2013-08-20 04:05 UTC
I've got an Capybara::Poltergeist::TimeoutError with a simple line of code:
```ruby
visit '/'
```

The debug output:

```
{"name"=>"set_debug", "args"=>[true]}
{"response"=>true}
{"name"=>"render", "args"=>["test.png", false]}
{"response"=>true}
{"name"=>"visit", "args"=>["http://127.0.0.1:54242/"]}
poltergeist [1376968991944] state default -> loading

Timed out waiting for response to {"name":"visit","args":["http://127.0.0.1:54242/"]}. 
It's possible that this happened because something
took a very long time (for example a page load was slow). 
If so, setting the Poltergeist :timeout
 option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker. (Capybara::Poltergeist::TimeoutError)
```

I'm not sure that it's a poltergeist bug.
Seems like the following code in the `web_socker_server.rb` raises the timeout exception:

```ruby
IO.select([socket], [], [], timeout) or raise Errno::EWOULDBLOCK
```

My environment:
Mac OS Lion 10.7.5
phantomjs-1.9.1
poltergeist-1.3.0

**Comment by agenteo** [comment] 2015-02-27 21:07
@ZachBeta tried your solution, looked really promising. After 3 days it's back.

To whoever posts a solution I'd love to hear for how long the flaky tests disappeared for.

If you run 10/15 builds a day you should wait at least one or two weeks before calling it gone. This is how we're trying to keep track of it http://teotti.com/a-process-to-identify-and-monitor-inconsistently-failing-automated-tests/#document-the-flaky-test

To others seeing this flaky test perhaps https://github.com/dblock/rspec-rerun or https://github.com/y310/rspec-retry might help.

**Comment by claptimes5** [comment] 2015-02-27 22:09
I've had this issue in the past and was wondering if everyone here has been using `database_cleaner`? I came across a recent issue where `database_cleaner` left open transactions in the database. This prevented the deletion or truncation calls from completing. Basically they timed out or hung forever.

https://github.com/DatabaseCleaner/database_cleaner/issues/292 
https://github.com/DatabaseCleaner/database_cleaner/issues/273

I made a fork that checks (hacks) if there are any open transactions when deleting/truncating (https://github.com/claptimes5/database_cleaner/commit/347b74b2ae2554e970ff3e9a5f63c3a6a4282f22. It's tough, since then poltergeist failures are intermittent, but can someone check and see if this helps?

**Comment by shedd** [comment] 2015-03-17 00:34
@claptimes5 thanks!  interesting theory.  we are using DatabaseCleaner and I gave your fork a try.  Unfortunately, we still hit the timeout errors.  It's possible that this may help, but I was unable to confirm that.

**Comment by claptimes5** [comment] 2015-03-17 01:59
@shedd What database are you using? I had to stop/start my instance to reset the sessions.

**Comment by shedd** [comment] 2015-03-17 06:28
Postgres.  We reproduced the timeouts on our CI service, so it's a fresh instance/container on each test run.

**Comment by Petercopter** [comment] 2015-03-31 21:40
+1 Using Postgres, database_cleaner, Capybara, Poltergeist, and Rails 4. Timing out. Still debugging. Working on Rails 3.x.

**Comment by andrewhao** [comment] 2015-03-31 22:54
On our project, none of the above solutions worked until we disabled `rack-timeout` in test environments: https://github.com/heroku/rack-timeout/issues/55

**Comment by showaltb** [comment] 2015-04-02 20:40
The problem for me is related to Ajax. Capybara makes a call to `driver.reset!` after every scenario. If an Ajax call is still running, I get the timeout error, with all subsequent tests failing.

If I wait for Ajax (wait for `page.evaluate_script('$.active > 0')` to become false), everything is good.

**Comment by shedd** [comment] 2015-04-03 06:20
>> On our project, none of the above solutions worked until we disabled rack-timeout in test environments: heroku/rack-timeout#55

Thanks @andrewhao - disabling rack-timeout was actually a big help for us!

**Comment by pmorton** [comment] 2015-04-28 17:48
Hi all. In our environment I found that the timeout was caused as a result of a lot of assets being rendered. From OSX I was able to use opensnoop (a dtrace tool) to see what files were being opened. Every time poltergeist would timeout, it was a result of the ruby process trying to compile assets. I achieved test stability by pre-compiling assets for test _and_ setting config.assets.digest = true.

**Comment by glennfu** [comment] 2015-05-01 16:25
I eventually had to abandon Poltergeist because of this error. I was using it to load external urls in a rake task to test if page was loading properly. The task would run once a minute opening up a cloudfront cdn cached page. Sometimes I would get the timeout error, most of the time I wouldn't. So there were no testing frameworks in the way or asset compilation issues to tinker with.

**Comment by mscottford** [comment] 2015-05-01 19:16
@glennfu: Sounds like your script would be a nice small example of this issue. Are you able to post a gist?

**Comment by glennfu** [comment] 2015-05-01 19:41
Here's the trimmed down version:

```
require 'capybara'
require 'capybara/dsl'
require 'capybara/poltergeist'

Capybara.run_server = false
Capybara.app_host = "http://america.aljazeera.com"

session = Capybara::Session.new(:poltergeist, nil)
session.visit "/"

success = !!(session.body =~ /Al Jazeera America/)
```

The kicker is that this was run once a minute on a clock thread and might not fail for hours. When it would fail, none of the other monitoring setups would detect any issues, and manually checking the site showed it was still loading just fine.

I removed the poltergeist code in August 2014, so it's been a while and it doesn't look like I wrote down the specific errors I was seeing. I just remember that it wasn't a capturable exception, the app would simply die. That was the biggest problem since I couldn't just rescue and retry.

I hope this is helpful!

**Comment by rschooley** [comment] 2015-05-07 16:11
For me this started when we added rack-timeout to my project.

After trying everything in this thread I stumbled into:
https://github.com/heroku/rack-timeout/issues/55

Leading me to this sample commit:
https://github.com/craftsmen/roll/commit/04c3d869764708ec8ff495c924117f8c5a3f48d0

Leaving this here incase it helps anyone else getting this issue for the same reason (it could happen for other reasons as well).

**Comment by qpowell** [comment] 2015-05-18 15:10
@rschooley using rack-timeout in production/staging only solved my issue as well. Thanks!

**Comment by razorcd** [comment] 2015-05-23 15:20
I can also confirm that moving `rack-timeout` gem  outside of the test environment fixed the poltergeist/phantomjs timeout issue.

Or setting the timeout to 0 also worked:
`Rack::Timeout.timeout = (Rails.env.test? ? 0 : 20)`

**Comment by markquezada** [comment] 2015-06-04 22:58
:+1: Moving `rack-timeout` out of the test group worked for me as well.

BTW, in `config/initializers/timeout.rb` I simply check if `Rack::Timeout` is defined before setting:

```ruby
if defined?(Rack::Timeout)
  Rack::Timeout.timeout = (ENV['RACK_TIMEOUT'] || 20).to_i
end
```

**Comment by sashamd** [comment] 2015-06-06 16:47
The error can be simulated with

Capybara.default_driver = :poltergeist
Capybara.current_session.driver.headers = {'User-Agent' => 'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:38.0) Gecko/20100101 Firefox/38.0'}

**Comment by andrewccadman** [comment] 2015-06-17 15:59
showaltb Ajax fixed for us - thanks a lot - we have had months of problems with this one.
Here is my slightly modified script if it's useful - we call  wait_for_ajax after in both AfterStep and the After hook.

def wait_for_ajax
  Timeout.timeout(Capybara.default_wait_time) do
    loop until finished_all_ajax_requests?
  end
end

def finished_all_ajax_requests?
  begin
    page.evaluate_script("(typeof jQuery !== \"undefined\") ? jQuery.active : 0").zero?
  rescue Exception => e
    puts e
  end
end

**Comment by jscottbruns** [comment] 2015-08-11 17:32
I was able to track this down an external js call taking a very long time and intermittently timing out. In my case the call was to an external service that does some rewriting of the page including some images. If I switch my driver to use webkit and include the option `block_unknown_urls` my tests run normally. 

```
Capybara.register_driver :webkit do |app|
  Capybara::Webkit::Driver.new(app).tap do |driver|
    driver.block_unknown_urls
  end
end
```

Since I haven't been able to find a similar option for poltergeist I was able to resolve the issue by including `--load-images=no` in the phantomjs options. Obviously this will break any tests that depend on loading images but in my case it's not a problem.

```
Capybara.register_driver :poltergeist do |app|
  options = {
    :window_size  => [1280, 1440],
    :port => 44678+ENV['TEST_ENV_NUMBER'].to_i,
    :phantomjs_options => ['--proxy-type=none', '--load-images=no', '--ignore-ssl-errors=yes', '--ssl-protocol=any'],
    :timeout => 120
  }
  Capybara::Poltergeist::Driver.new(app, options)
end
```

**Comment by house9** [comment] 2015-09-02 22:53
I was encountering `Capybara::Poltergeist::TimeoutError` errors in my feature specs under the following circumstances

* `js: true`
* and cdn references that were using https in my layouts

changing the cdn references to use Protocol-relative fixed the issue, i.e.:

`<%= javascript_include_tag "//code.jquery.com/jquery-2.1.4.min.js" %>`

this was running my specs on a vagrant box with ubuntu 14.04; phantomjs 1.9.0 and with poltergeist 1.5.1

**Comment by twalpole** [comment] 2015-11-14 20:54
I'm closing this since it doesn't actually appear to be a specific issue but a collection of 5 or 6 different things.  From a quick perusal it appears using the blacklist support added in 1.6.0 and telling phantomjs to ignore ssl errors may have fixed some of them for people, but other than that it's a lot of crosstalk.  If anyone is still having issues with current poltergeist please open a new issue with all relevant details and if possible a minimal test case.

**Closed by twalpole** 2015-11-14 20:54 UTC

**Comment by Vanuan** [comment] 2015-12-08 04:00
@twalpole what is current phantomjs? 2.0.0 still not released.

**Comment by twalpole** [comment] 2015-12-08 06:35
@Vanuan Phantomjs 2.0.0 was released Jan 24, 2015 - so almost a year ago

**Comment by Vanuan** [comment] 2015-12-08 20:55
@twalpole still, there are no official binaries for Linux

**Comment by twalpole** [comment] 2015-12-08 21:15
@Vanuan That really seems likes an issue to post over on the phantomjs project and not actually a  poltergeist issue.  You could also just compile it yourself for whatever platform you want to run it on.

**Comment by Senjai** [comment] 2015-12-09 00:46
@twalpole I would be pro locking this issue down, as I suspect it will still generate new comments, and a lot of pings if that's something you'd be okay with.

**Comment by twalpole** [comment] 2015-12-09 01:00
@Senjai Done
