### ISSUE TITLE
Problem with find

### ISSUE THREAD

**Issue by thiagogsr** [teampoltergeist/poltergeist#653] opened 2015-09-16 18:35 UTC
Hi there,

Randomly an error occurs when I call `find`, `fill`, `all`, anything. 

The problem is on this method (line 62)
https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/browser.rb#L60-L63

The error is different each time.
`NoMethodError: undefined method '[]' for nil:NilClass`
`NoMethodError: undefined method 'map' for false:FalseClass`

So sometimes `result` is `nil`, but sometimes `result['ids']` is `True` or `False`.

Is it a thread issue?

**Comment by thiagogsr** [comment] 2015-09-16 20:23
Debug log:
```
# ...
{"name":"visible","args":[2,5038]}
{"response":{"page_id":2,"ids":[5039,5040,5041,5042,5043]}}
{"name":"find_within","args":[2,5038,"xpath","(preceding-sibling::tr[contains(@class,'css-xxx')])[1]"]}
{"response":false}
{"name":"switch_to_window","args":["0"]}
{"response":[]}
rake aborted!
NoMethodError: undefined method `map' for false:FalseClass
```

**Comment by route** [comment] 2015-09-16 20:27
@thiagogsr please show the test

**Comment by thiagogsr** [comment] 2015-09-16 20:34
I'm using for a form filler, whatever, I'm using these methods

```def method1
    all('#selector-xxx span-xxx')
  end

  def method2?
    using_wait_time 2 do
      return unless wait_and_check_existance '#selector-yyy'
      find('#selector-zzz').trigger('click')
      true
    end
  end

  def method3(node)
    value1 = node.find(:xpath, "(preceding-sibling::tr[contains(@class,'css-class-xxx')])[1]").text
    value2 = node.all('td')[2].text
    "#{value1} - #{value2}"
  end
```

Please sorry for the name methods, I needed hide them

**Comment by ahorek** [comment] 2015-09-16 23:18
I've got the same problem, but it's totaly random, I can't reproduce it. Maybe it's related to:
https://github.com/teampoltergeist/poltergeist/issues/482
https://github.com/alexgirdler/poltergeist/commit/77943021d364d5d265ec007485d9b8760ee0642b

**Comment by twalpole** [comment] 2015-09-29 17:38
What version of poltergeist are you using?   Looking through the code - a response of nil, false, or true isn't theoretically possible for find or find_within, however from a quick glance (not a through analysis so I could be wrong) it does look like it may be possible for the responses to get out of sync if you were using poltergeist simultaneously from multiple threads.  Are you using multiple threads and accessing poltergeist from them simultaneously?

**Comment by thiagogsr** [comment] 2015-09-29 17:42
I'm using v1.6.0 and I'm not using multiple threads, but the problem happens inside a ruby loop.

**Comment by twalpole** [comment] 2015-09-29 17:51
It also appears to be possible for responses to get out of sync if a TimeoutError is thrown while waiting for a response, if that TimeoutError is caught somwhere and a new command issued to poltergesit

**Comment by twalpole** [comment] 2015-09-29 17:55
From the log you posted it definitely looks like the responses are out of sync - ie    response: false probably should be with  the 'visible' command -- response [] should be with the find_within command

**Comment by thiagogsr** [comment] 2015-09-29 17:56
Are you seeing a way to fix it?

**Comment by twalpole** [comment] 2015-09-29 18:01
Short term you could try increasing the server timeout -- longer term maybe implement command ids to ensure the response is for the current command, not really sure at the moment.

**Comment by twalpole** [comment] 2015-09-29 20:38
@thiagogsr Do you have more of the log you posted???  It would be interesting/beneficial to see where the responses went out of sync.

**Comment by twalpole** [comment] 2015-09-29 20:48
This is caused by the same issue as #482

**Comment by thiagogsr** [comment] 2015-09-30 00:43
@twalpole I don't have more logs because I needed abort the poltergeist usage in this case. The log sent is an example, `find_within` is not the problem, this issue happens for any method. I believe the problem is the sync like you said. Maybe a phantomjs bug...

**Comment by thiagogsr** [comment] 2015-09-30 00:44
@darthjee follow here

**Comment by twalpole** [comment] 2015-09-30 03:03
It's an issue where a response isn't picked up, and then the next command sent gets the response for the previous command. I'm working on potentially adding request ids so the response and request can be matched up - might be a couple of days

**Comment by thiagogsr** [comment] 2015-09-30 15:45
If you write a loop filling an input, maybe you can see the error. I will try here too.

**Comment by twalpole** [comment] 2015-10-02 23:08
I believe PR #668 should fix this, although I was unable to create a test case for it --  could you give it a try?

**Comment by thiagogsr** [comment] 2015-10-03 12:28
@twalpole you're a awesome guy. It works perfectly, congratulations. Waiting merge, then I will "run for the hug" (popular brazilian expression :smile:).

**Comment by twalpole** [comment] 2015-10-09 16:45
This should be fixed since PR #668 was merged in - if not we can reopen

**Comment by thiagogsr** [comment] 2015-10-09 16:46
Sure, waiting a new release :)

**Closed by twalpole** 2015-10-09 16:45 UTC

**Comment by TakaakiFuruse** [comment] 2015-11-01 01:17
@twalpole 

I am having the same error when I visit specific website.
(I am not sure whether this is the right place to ask, since I'm trying to use poltergeist as a scraper not testing environment.)

The error is
gems/poltergeist-1.7.0/lib/capybara/poltergeist/browser.rb:63:in `find': undefined method `map' for nil:NilClass (NoMethodError)

What I want to do is automatically login a website.
For example, If I do this.

```ruby
require "capybara"
require "capybara/dsl"
require 'capybara/poltergeist'
include Capybara::DSL

class Scraper

  include Capybara::DSL
  attr_accessor :click_sec, :goouk

  def initialize
    @click_sec = 'https://sec-sso.click-sec.com/loginweb/'
    @goouk = 'https://www.google.co.uk'
    Capybara.current_driver = :poltergeist
    Capybara.javascript_driver = :poltergeist
    Capybara.register_driver :poltergeist do |app|
      Capybara::Poltergeist::Driver.new(app, {timeout: 120, js_errors: false, phantomjs_options: ['--load-images=no', '--ignore-ssl-errors=yes'], :debug => true})
    end
  end

  def to_click_sec
    visit(click_sec)
    p has_button? "Login"
  end

  def to_google
    visit(goouk)
    p has_link? "Gmail"
  end
end

Scraper.new.to_google # => this works fine
Scraper.new.to_click_sec # => this is not
```
Debug message for "Scraper.new.to_click_sec" is here.

```
{"id":"9d99eeb4-56ee-4ea4-b234-a59e1394d960","name":"set_js_errors","args":[false]}
{"command_id":"9d99eeb4-56ee-4ea4-b234-a59e1394d960","response":true}
{"id":"379f2e1a-5895-4d2b-9c3b-39f4318b9953","name":"set_debug","args":[true]}
{"command_id":"379f2e1a-5895-4d2b-9c3b-39f4318b9953","response":true}
{"id":"391580ad-2d9f-4613-9454-c12a65e9fefc","name":"visit","args":["https://sec-sso.click-sec.com/loginweb/"]}
{"command_id":"391580ad-2d9f-4613-9454-c12a65e9fefc","response":{"status":"success"}}
{"id":"947f0f1b-8188-47a5-99fd-668edd4a974d","name":"find","args":["xpath",".//input[./@type = 'submit' or ./@type = 'reset' or ./@type = 'image' or ./@type = 'button'][((./@id = 'Login' or contains(./@value, 'Login')) or contains(./@title, 'Login'))] | .//input[./@type = 'image'][contains(./@alt, 'Login')] | .//button[(((./@id = 'Login' or contains(./@value, 'Login')) or contains(normalize-space(string(.)), 'Login')) or contains(./@title, 'Login'))] | .//input[./@type = 'image'][contains(./@alt, 'Login')]"]}
{"command_id":"947f0f1b-8188-47a5-99fd-668edd4a974d","response":{"page_id":1}}
/home/orz/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/poltergeist-1.7.0/lib/capybara/poltergeist/browser.rb:63:in `find': undefined method `map' for nil:NilClass (NoMethodError)
        from /home/orz/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/poltergeist-1.7.0/lib/capybara/poltergeist/driver.rb:120:in `find'
        from /home/orz/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/poltergeist-1.7.0/lib/capybara/poltergeist/driver.rb:124:in `find_xpath'
        from /home/orz/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.5.0/lib/capybara/node/base.rb:107:in `find_xpath'
        from /home/orz/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.5.0/lib/capybara/query.rb:110:in `block in resolve_for'
        from /home/orz/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.5.0/lib/capybara/node/base.rb:80:in `synchronize'
        from /home/orz/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.5.0/lib/capybara/query.rb:106:in `resolve_for'
        from /home/orz/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.5.0/lib/capybara/node/matchers.rb:94:in `block in assert_selector'
        from /home/orz/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.5.0/lib/capybara/node/base.rb:84:in `synchronize'
        from /home/orz/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.5.0/lib/capybara/node/matchers.rb:93:in `assert_selector'
        from /home/orz/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.5.0/lib/capybara/node/matchers.rb:39:in `has_selector?'
        from /home/orz/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.5.0/lib/capybara/node/matchers.rb:251:in `has_button?'
        from /home/orz/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.5.0/lib/capybara/session.rb:698:in `block (2 levels) in <class:Session>'
        from /home/orz/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.5.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
        from google.rb:23:in `to_click_sec'
        from google.rb:34:in `<main>'
```
phamtomjs is 1.9.8 and poltergeist is from master brunch.

**Comment by twalpole** [comment] 2015-11-01 03:05
@TakaakiFuruse  - Your error is different but similar -- as you can see from the previous logs above, find was sometimes "returning" an error of false which just shouldn't be possible, in your case it's at least returning a page_id -- but that also isn't quite enough -- please add your info as a separate issue, and I'll try and take a look at it tomorrow

**Comment by TakaakiFuruse** [comment] 2015-11-01 03:08
@twalpole 
>please add your info as a separate issue,
Thanks for your response. I would do so.
