### ISSUE TITLE
Scroll/click firing at wrong coordinates - Poltergeist detected another element with CSS selector '' at this position.

### ISSUE THREAD

**Issue by sbull** [teampoltergeist/poltergeist#520] opened 2014-08-02 21:30 UTC
I've narrowed down a bug to what appears to be an issue with scrolling and clicking. Take the following:

`public/bug.html`:
```html
<!DOCTYPE html>
<html>
  <head></head>
  <body>

<div style="height:800px; width:100%; background-color:pink;"></div>

<a href="#">
  <div>CLICK HERE</div>
</a>

  </body>
</html>
```

`spec/features/bug_spec.rb`:
```ruby
require 'spec_helper'

feature "BUG" do

  scenario "poltergeist scroll bug" do
    visit '/bug.html'
    click_on "CLICK HERE"
  end

  scenario "poltergeist resized" do
    visit '/bug.html'
    page.driver.resize(786, 1024)
    click_on "CLICK HERE"
  end

end
```

`spec/spec_helper.rb` is pretty standard, here are the relevant bits:
```ruby
require 'capybara/poltergeist'
Capybara.default_driver = :poltergeist
```

And here's what I get when I run `rspec spec/features/bug_spec.rb`:
```
F.

Failures:

  1) BUG poltergeist scroll bug
     Failure/Error: click_on "CLICK HERE"
     Capybara::Poltergeist::MouseEventFailed:
       Firing a click at co-ordinates [8, 788] failed. Poltergeist detected another element with CSS selector '' at this position. It may be overlapping the element you are trying to interact with. If you don't care about overlapping elements, try using node.trigger('click').
     # ./spec/features/bug_spec.rb:7:in `block (2 levels) in <top (required)>'

Finished in 4.83 seconds
2 examples, 1 failure

Failed examples:

rspec ./spec/features/bug_spec.rb:5 # BUG poltergeist scroll bug

Randomized with seed 10240
```

The debug log doesn't add much info, just that the click at those coordinates is failing, but here it is (with `Capybara.default_wait_time = 0`):
```
{"name"=>"set_debug", "args"=>[true]}
{"response"=>true}
{"name"=>"visit", "args"=>["http://127.0.0.1:56227/bug.html"]}
poltergeist [1407014635392] state default -> loading
poltergeist [1407014635450] state loading -> default
{"response"=>{"status"=>"success"}}
{"name"=>"find", "args"=>[:xpath, ".//a[./@href][(((./@id = 'CLICK HERE' or normalize-space(string(.)) = 'CLICK HERE') or ./@title = 'CLICK HERE') or .//img[./@alt = 'CLICK HERE'])] | .//input[./@type = 'submit' or ./@type = 'reset' or ./@type = 'image' or ./@type = 'button'][((./@id = 'CLICK HERE' or ./@value = 'CLICK HERE') or ./@title = 'CLICK HERE')] | .//input[./@type = 'image'][./@alt = 'CLICK HERE'] | .//button[(((./@id = 'CLICK HERE' or ./@value = 'CLICK HERE') or normalize-space(string(.)) = 'CLICK HERE') or ./@title = 'CLICK HERE')] | .//input[./@type = 'image'][./@alt = 'CLICK HERE']"]}
{"response"=>{"page_id"=>1, "ids"=>[0]}}
{"name"=>"visible", "args"=>[1, 0]}
{"response"=>true}
{"name"=>"tag_name", "args"=>[1, 0]}
{"response"=>"A"}
{"name"=>"click", "args"=>[1, 0]}
poltergeist [1407014635517] state default -> mouse_event
{"error"=>{"name"=>"Poltergeist.MouseEventFailed", "args"=>["click", nil, {"x"=>8, "y"=>788}]}}
{"name"=>"reset", "args"=>[]}
poltergeist [1407014635536] state mouse_event -> default
{"response"=>true}
{"name"=>"find", "args"=>[:xpath, "/html/body/*"]}
{"response"=>{"page_id"=>1, "ids"=>[]}}
```

Versions:
poltergeist 1.5.1 (capybara 2.2.1)
phantomjs 1.9.7 (node v0.10.17)
ruby 2.0.0p353
Ubuntu 12.04, running headless in a virtual machine.

(FYI: discovered this while working on https://github.com/sbull/capybara-paparazzi)

**Comment by rodrigopinto** [comment] 2015-01-30 00:00
I encountered this problem in scenarios in that use javascript and need `js: true`. 

I fixed it changing `click_link` by `trigger("click")` i.e:

```ruby
# How I came across with the problem 
click_link("Add to cart")

#How I solved
find("a", text: "Add to cart").trigger("click")
````

**Comment by skovsboll** [comment] 2015-02-02 10:07
Click_link() does a lot more than find(). If you replace click_link you have to rewrite many of your selectors.
Here's a monkey patch that will allow you to continue using click_link, click_button etc. with seleniun and phantonjs:

```
class Capybara::Node::Element

  alias :old_click :click if method_defined? :click

  def click
    trigger('click')
  rescue Capybara::NotSupportedByDriverError
    old_click
  end
end
```

**Comment by leishman** [comment] 2015-03-23 06:15
I added a conditional in my `acceptance_helper` file so that I don't have to go changing all of my specs that use `click_link`. It looks like this:

```ruby
# If environment is running on Jenkins CI, use headless PhantomJS configuration
if ENV["CI"].to_b
  # configure your headless acceptance test settings
  # overwrite default click_link method to use trigger
  Capybara::Node::Actions.send(:define_method, :click_link) { |text| find('a', text: text).trigger('click') }
else
  # configure your in-browser acceptance test settings
end
```

**Comment by MrHubble** [comment] 2015-03-30 06:14
@skovsboll does that also apply to `click_on`. I've just started using Capybara and have read that I should use Poltergeist to be able to test my js with Capybara. I had code with `click_on` that was working before I added Poltergeist but now is not. 

Is there anywhere in particular I should add your monkey patch or will something like config/capybara_monkey_patch.rb do?

**Comment by MrHubble** [comment] 2015-04-02 23:53
I ended up adding the fix suggested by @skovsboll to the bottom of my `test_helper.rb` and the `Scroll/click firing at wrong coordinates - Poltergeist detected another element with CSS selector '' at this position` error no longer occurs but my clicks no longer work in that the app does not click through to the next page.

I will try `trigger("click")` as mentioned in multiple comments above and is also the accepted answer in here: http://stackoverflow.com/a/19814764/1299792

**Comment by ot-brian-mackey** [comment] 2015-08-12 20:18
@marionzualo The window size you recommended worked!  Thanks I fought this for hours!

**Comment by twalpole** [comment] 2015-11-10 18:01
@route  Looking at the initial example posted here, what poltergeist does when firing mouse events is shown here https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/client/node.coffee#L32

The first step is to scroll whatever element is being interacted with by called Node#scrollIntoView which calls scrollIntoViewIfNeeded() on the native  element in the page.   The strange thing is that this doesn't actually appear to scroll the page in this page - if instead we call scrollIntoView() on the native element then it does scroll and the test passes.  I need to look into scrollIntoViewIfNeeded to see why it isn't working, but it may be easier just to swap to scrollIntoView() and live with any small slowdown excess scrolling may cause -- or maybe just check if the click position would be outside the window and call scrollIntoView then

**Comment by twalpole** [comment] 2015-11-10 22:40
Ok -- after looking at this some more it appears scrollIntoViewIfNeeded doesn't scroll an element into view if it has no dimensions -- In the initial failing example the <a> element has a <div> inside it - because the <a> element is inline by default, the block element size inside it doesn't contribute to it's dimensions so the <a> element technically has 0 height and 0 width, hence not scrolled into view.  Changing the display style of the <a> element to inline-block then takes into account the block content inside, gives it dimension and then it gets scrolled into view --  not sure if we should apply PR #691 or whether we should just consider it expected behavior (or throw an error, etc)

**Comment by twalpole** [comment] 2015-11-11 23:05
PR #691, which was just merged into master , should fix the original example this was issue was about, If there are other problems where clicks are occurring incorrectly please create minimal examples that exhibit the behavior and create new issues for them -  resorting to trigger('click') really is not a good idea when testing web apps (if used for scraping data from sites it may be perfectly fine)

**Closed by twalpole** 2015-11-11 23:05 UTC

**Comment by YangaMGMT** [comment] 2016-03-22 12:10
Thanks @marionzualo, was struggling to fix our build for a while and changing the window size worked like a charm.
