### ISSUE TITLE
Select boxes always appear in the top right corner in screen shots

### ISSUE THREAD

**Issue by donv** [teampoltergeist/poltergeist#570] opened 2015-01-10 23:29 UTC
Hi!

We just started using poltergeist instead of selenium-webdriver.  All works well except that select boxes are all rendered in the top left corner.  Is this known issue, or am I doing something wrong?

selenium-webdriver:

![shift_summary](https://cloud.githubusercontent.com/assets/57275/5693671/c4de122a-9928-11e4-9b2d-330a664f80bb.png)

poltergeist:

![shift_summary](https://cloud.githubusercontent.com/assets/57275/5693668/ab490f54-9928-11e4-9c15-2eca2feba3a2.png)

**Comment by yaauie** [comment] 2015-01-10 23:44
Poltergeist doesn't actually do any rendering; this project is just an adapter between Capybara (the ruby-based web testing framweork) and PhantomJS (which is effectively a "virtual" web browser, based on the WebKit rendering engine), and we translate commands from your ruby-based test code to and from the PhantomJS VM.

There are a number of things that could cause an element to display differently in one web browser vs another, and most of those things work pretty consistently within a given rendering engine, so your best bet to start debugging is to use a WebKit-based browser (like Chrome) to visually verify the behaviour.

If Chrome displays the content correctly, I would be glad to help you get a small, reproducible test case together (so we can send it on to the PhantomJS project), but first there are a couple things you can check.

1. Is your phantomjs executable up-to-date? `phantomjs --version`
2. What versions are you using of:
  - ruby `ruby --version`
  - capybara `gem list --local | grep capybara`
  - poltergeist `gem list --local | grep poltergeist`

What is the smallest bit of code that exhibits the behaviour? Do the form elements that are improperly positioned have any CSS rules applied to them?

**Comment by donv** [comment] 2015-01-11 01:40
Hi @yaauie !

Thanks for your quick answer.

    $ phantomjs --version
    1.9.8

I use JRuby 1.7.13, 1.7.16.1, and 1.7.18.

capybara (2.3.0)
poltergeist (1.5.1)

I can try running on MRI if it helps.

I will start work on making a minimal example.  The select elements do have CSS attached to them.  I will investigate more.

**Comment by twalpole** [comment] 2015-11-13 21:03
Closing due to age of the info -- If you're still having this issue with phantomjs 2+ and the latest poltergeist we can reopen

**Closed by twalpole** 2015-11-13 21:03 UTC
